// Copyright 2021-2026 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0
// Access requests: the PEP-facing contract for asking Cerbos Hub for the
// access a requestable deny withheld.
//
// A requestable deny is a deny decision whose rule declared an escalation
// marker in the reserved `cerbos.accessRequest` output. The application (the
// PEP) submits that denied evaluation here as an access request. Hub verifies
// it against the decision log entry it claims to be bound to, routes it to an
// approver and, if the request is approved, issues a time-boxed approval
// token. Completion is reevaluation: the PEP presents the token in
// `aux_data.jwts["approval"]` on a fresh check and policy decides. Hub never
// answers "allowed" on its own, and every approval expires.
//
// # Identifiers
//
// Access request and approval ids are 12 characters from 0-9A-Z, like every
// other id shown in the Hub UI and API. Evaluation ids are the 26-character
// ULID call ids the PDP assigns to each check (`cerbos_call_id`) and records in
// its decision log.

// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cerbos/cloud/accessrequest/v1/accessrequest.proto

package accessrequestv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/cerbos/cloud-api/genpb/cerbos/cloud/accessrequest/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AccessRequestServiceName is the fully-qualified name of the AccessRequestService service.
	AccessRequestServiceName = "cerbos.cloud.accessrequest.v1.AccessRequestService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AccessRequestServiceCancelAccessRequestProcedure is the fully-qualified name of the
	// AccessRequestService's CancelAccessRequest RPC.
	AccessRequestServiceCancelAccessRequestProcedure = "/cerbos.cloud.accessrequest.v1.AccessRequestService/CancelAccessRequest"
	// AccessRequestServiceGetAccessRequestProcedure is the fully-qualified name of the
	// AccessRequestService's GetAccessRequest RPC.
	AccessRequestServiceGetAccessRequestProcedure = "/cerbos.cloud.accessrequest.v1.AccessRequestService/GetAccessRequest"
	// AccessRequestServiceSubmitAccessRequestProcedure is the fully-qualified name of the
	// AccessRequestService's SubmitAccessRequest RPC.
	AccessRequestServiceSubmitAccessRequestProcedure = "/cerbos.cloud.accessrequest.v1.AccessRequestService/SubmitAccessRequest"
)

// AccessRequestServiceClient is a client for the cerbos.cloud.accessrequest.v1.AccessRequestService
// service.
type AccessRequestServiceClient interface {
	// CancelAccessRequest withdraws a pending request. Any API key of the same
	// workspace may cancel it.
	//
	//   - FAILED_PRECONDITION: the request is no longer pending
	//     (`invalid_task_state`).
	//   - NOT_FOUND: no request with that id exists in the caller's workspace.
	CancelAccessRequest(context.Context, *connect.Request[v1.CancelAccessRequestRequest]) (*connect.Response[v1.CancelAccessRequestResponse], error)
	// GetAccessRequest reads a request, including the approval token once the
	// request is approved. Any API key of the same workspace may read it, so
	// the id can be handed from the submitter to whichever component performs
	// the reevaluation.
	//
	//   - NOT_FOUND: no request with that id exists in the caller's workspace.
	GetAccessRequest(context.Context, *connect.Request[v1.GetAccessRequestRequest]) (*connect.Response[v1.GetAccessRequestResponse], error)
	// SubmitAccessRequest creates a pending request bound to a denied
	// evaluation and notifies the workspace's approvers.
	//
	//   - INVALID_ARGUMENT: the denial is not requestable, that is its rule
	//     declared no escalation marker (`not_requestable`); the denial does not
	//     bind to a single evaluation, for example the marker or actions do not
	//     belong to the rule named by `rule_src` (`invalid_denial_binding`); or
	//     the marker fails the rules on AccessRequestMarker (malformed marker).
	//   - FAILED_PRECONDITION: `denial.evaluated_at` is older than the
	//     workspace's request window (`expired_denial`).
	//   - ALREADY_EXISTS: `idempotency_key` was already used by this API key
	//     for a different evaluation, as compared by evaluation id, principal
	//     id, resource kind and id, and actions (`duplicate_request`).
	SubmitAccessRequest(context.Context, *connect.Request[v1.SubmitAccessRequestRequest]) (*connect.Response[v1.SubmitAccessRequestResponse], error)
}

// NewAccessRequestServiceClient constructs a client for the
// cerbos.cloud.accessrequest.v1.AccessRequestService service. By default, it uses the Connect
// protocol with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed
// requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAccessRequestServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AccessRequestServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	accessRequestServiceMethods := v1.File_cerbos_cloud_accessrequest_v1_accessrequest_proto.Services().ByName("AccessRequestService").Methods()
	return &accessRequestServiceClient{
		cancelAccessRequest: connect.NewClient[v1.CancelAccessRequestRequest, v1.CancelAccessRequestResponse](
			httpClient,
			baseURL+AccessRequestServiceCancelAccessRequestProcedure,
			connect.WithSchema(accessRequestServiceMethods.ByName("CancelAccessRequest")),
			connect.WithClientOptions(opts...),
		),
		getAccessRequest: connect.NewClient[v1.GetAccessRequestRequest, v1.GetAccessRequestResponse](
			httpClient,
			baseURL+AccessRequestServiceGetAccessRequestProcedure,
			connect.WithSchema(accessRequestServiceMethods.ByName("GetAccessRequest")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		submitAccessRequest: connect.NewClient[v1.SubmitAccessRequestRequest, v1.SubmitAccessRequestResponse](
			httpClient,
			baseURL+AccessRequestServiceSubmitAccessRequestProcedure,
			connect.WithSchema(accessRequestServiceMethods.ByName("SubmitAccessRequest")),
			connect.WithClientOptions(opts...),
		),
	}
}

// accessRequestServiceClient implements AccessRequestServiceClient.
type accessRequestServiceClient struct {
	cancelAccessRequest *connect.Client[v1.CancelAccessRequestRequest, v1.CancelAccessRequestResponse]
	getAccessRequest    *connect.Client[v1.GetAccessRequestRequest, v1.GetAccessRequestResponse]
	submitAccessRequest *connect.Client[v1.SubmitAccessRequestRequest, v1.SubmitAccessRequestResponse]
}

// CancelAccessRequest calls cerbos.cloud.accessrequest.v1.AccessRequestService.CancelAccessRequest.
func (c *accessRequestServiceClient) CancelAccessRequest(ctx context.Context, req *connect.Request[v1.CancelAccessRequestRequest]) (*connect.Response[v1.CancelAccessRequestResponse], error) {
	return c.cancelAccessRequest.CallUnary(ctx, req)
}

// GetAccessRequest calls cerbos.cloud.accessrequest.v1.AccessRequestService.GetAccessRequest.
func (c *accessRequestServiceClient) GetAccessRequest(ctx context.Context, req *connect.Request[v1.GetAccessRequestRequest]) (*connect.Response[v1.GetAccessRequestResponse], error) {
	return c.getAccessRequest.CallUnary(ctx, req)
}

// SubmitAccessRequest calls cerbos.cloud.accessrequest.v1.AccessRequestService.SubmitAccessRequest.
func (c *accessRequestServiceClient) SubmitAccessRequest(ctx context.Context, req *connect.Request[v1.SubmitAccessRequestRequest]) (*connect.Response[v1.SubmitAccessRequestResponse], error) {
	return c.submitAccessRequest.CallUnary(ctx, req)
}

// AccessRequestServiceHandler is an implementation of the
// cerbos.cloud.accessrequest.v1.AccessRequestService service.
type AccessRequestServiceHandler interface {
	// CancelAccessRequest withdraws a pending request. Any API key of the same
	// workspace may cancel it.
	//
	//   - FAILED_PRECONDITION: the request is no longer pending
	//     (`invalid_task_state`).
	//   - NOT_FOUND: no request with that id exists in the caller's workspace.
	CancelAccessRequest(context.Context, *connect.Request[v1.CancelAccessRequestRequest]) (*connect.Response[v1.CancelAccessRequestResponse], error)
	// GetAccessRequest reads a request, including the approval token once the
	// request is approved. Any API key of the same workspace may read it, so
	// the id can be handed from the submitter to whichever component performs
	// the reevaluation.
	//
	//   - NOT_FOUND: no request with that id exists in the caller's workspace.
	GetAccessRequest(context.Context, *connect.Request[v1.GetAccessRequestRequest]) (*connect.Response[v1.GetAccessRequestResponse], error)
	// SubmitAccessRequest creates a pending request bound to a denied
	// evaluation and notifies the workspace's approvers.
	//
	//   - INVALID_ARGUMENT: the denial is not requestable, that is its rule
	//     declared no escalation marker (`not_requestable`); the denial does not
	//     bind to a single evaluation, for example the marker or actions do not
	//     belong to the rule named by `rule_src` (`invalid_denial_binding`); or
	//     the marker fails the rules on AccessRequestMarker (malformed marker).
	//   - FAILED_PRECONDITION: `denial.evaluated_at` is older than the
	//     workspace's request window (`expired_denial`).
	//   - ALREADY_EXISTS: `idempotency_key` was already used by this API key
	//     for a different evaluation, as compared by evaluation id, principal
	//     id, resource kind and id, and actions (`duplicate_request`).
	SubmitAccessRequest(context.Context, *connect.Request[v1.SubmitAccessRequestRequest]) (*connect.Response[v1.SubmitAccessRequestResponse], error)
}

// NewAccessRequestServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAccessRequestServiceHandler(svc AccessRequestServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	accessRequestServiceMethods := v1.File_cerbos_cloud_accessrequest_v1_accessrequest_proto.Services().ByName("AccessRequestService").Methods()
	accessRequestServiceCancelAccessRequestHandler := connect.NewUnaryHandler(
		AccessRequestServiceCancelAccessRequestProcedure,
		svc.CancelAccessRequest,
		connect.WithSchema(accessRequestServiceMethods.ByName("CancelAccessRequest")),
		connect.WithHandlerOptions(opts...),
	)
	accessRequestServiceGetAccessRequestHandler := connect.NewUnaryHandler(
		AccessRequestServiceGetAccessRequestProcedure,
		svc.GetAccessRequest,
		connect.WithSchema(accessRequestServiceMethods.ByName("GetAccessRequest")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	accessRequestServiceSubmitAccessRequestHandler := connect.NewUnaryHandler(
		AccessRequestServiceSubmitAccessRequestProcedure,
		svc.SubmitAccessRequest,
		connect.WithSchema(accessRequestServiceMethods.ByName("SubmitAccessRequest")),
		connect.WithHandlerOptions(opts...),
	)
	return "/cerbos.cloud.accessrequest.v1.AccessRequestService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AccessRequestServiceCancelAccessRequestProcedure:
			accessRequestServiceCancelAccessRequestHandler.ServeHTTP(w, r)
		case AccessRequestServiceGetAccessRequestProcedure:
			accessRequestServiceGetAccessRequestHandler.ServeHTTP(w, r)
		case AccessRequestServiceSubmitAccessRequestProcedure:
			accessRequestServiceSubmitAccessRequestHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAccessRequestServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAccessRequestServiceHandler struct{}

func (UnimplementedAccessRequestServiceHandler) CancelAccessRequest(context.Context, *connect.Request[v1.CancelAccessRequestRequest]) (*connect.Response[v1.CancelAccessRequestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.accessrequest.v1.AccessRequestService.CancelAccessRequest is not implemented"))
}

func (UnimplementedAccessRequestServiceHandler) GetAccessRequest(context.Context, *connect.Request[v1.GetAccessRequestRequest]) (*connect.Response[v1.GetAccessRequestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.accessrequest.v1.AccessRequestService.GetAccessRequest is not implemented"))
}

func (UnimplementedAccessRequestServiceHandler) SubmitAccessRequest(context.Context, *connect.Request[v1.SubmitAccessRequestRequest]) (*connect.Response[v1.SubmitAccessRequestResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cerbos.cloud.accessrequest.v1.AccessRequestService.SubmitAccessRequest is not implemented"))
}
