// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0

package notificationsv1

import (
	v11 "github.com/cerbos/cerbos/api/genpb/cerbos/engine/v1"
	v1 "github.com/cerbos/cloud-api/genpb/cerbos/cloud/accessrequest/v1"
	protowire "google.golang.org/protobuf/encoding/protowire"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	hash "hash"
	maps "maps"
	math "math"
	slices "slices"
	sync "sync"
	unsafe "unsafe"
)

var hashpb_bufPool = sync.Pool{
	New: func() any { return new([10]byte) },
}

var hashpb_stringKeyPool = sync.Pool{
	New: func() any { return make([]string, 0, 32) },
}

var hashpb_int32KeyPool = sync.Pool{
	New: func() any { return make([]int32, 0, 32) },
}

var hashpb_int64KeyPool = sync.Pool{
	New: func() any { return make([]int64, 0, 32) },
}

var hashpb_uint32KeyPool = sync.Pool{
	New: func() any { return make([]uint32, 0, 32) },
}

var hashpb_uint64KeyPool = sync.Pool{
	New: func() any { return make([]uint64, 0, 32) },
}

func cerbos_cloud_accessrequest_v1_AccessRequestMarker_hashpb_sum(m *v1.AccessRequestMarker, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.AccessRequestMarker.approver"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetApprover()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetApprover()), len(m.GetApprover())))
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.AccessRequestMarker.approval_ttl"]; !ok {
		if m.GetApprovalTtl() != nil {
			google_protobuf_Duration_hashpb_sum(m.GetApprovalTtl(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.AccessRequestMarker.reason"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetReason()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetReason()), len(m.GetReason())))
	}
}

func cerbos_cloud_accessrequest_v1_AccessRequest_hashpb_sum(m *v1.AccessRequest, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.AccessRequest.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.AccessRequest.status"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetStatus())))
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.AccessRequest.denial"]; !ok {
		if m.GetDenial() != nil {
			cerbos_cloud_accessrequest_v1_DeniedEvaluation_hashpb_sum(m.GetDenial(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.AccessRequest.verification"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetVerification())))
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.AccessRequest.justification"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetJustification()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetJustification()), len(m.GetJustification())))
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.AccessRequest.actor"]; !ok {
		if m.GetActor() != nil {
			cerbos_cloud_accessrequest_v1_Actor_hashpb_sum(m.GetActor(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.AccessRequest.approval"]; !ok {
		if m.GetApproval() != nil {
			cerbos_cloud_accessrequest_v1_Approval_hashpb_sum(m.GetApproval(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.AccessRequest.created_at"]; !ok {
		if m.GetCreatedAt() != nil {
			google_protobuf_Timestamp_hashpb_sum(m.GetCreatedAt(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.AccessRequest.expires_at"]; !ok {
		if m.GetExpiresAt() != nil {
			google_protobuf_Timestamp_hashpb_sum(m.GetExpiresAt(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_accessrequest_v1_Actor_hashpb_sum(m *v1.Actor, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.Actor.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.Actor.type"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetType()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetType()), len(m.GetType())))
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.Actor.act"]; !ok {
		if len(m.Act) > 0 {
			for _, v := range m.Act {
				if v != nil {
					cerbos_cloud_accessrequest_v1_Actor_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
}

func cerbos_cloud_accessrequest_v1_Approval_hashpb_sum(m *v1.Approval, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.Approval.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.Approval.approved_at"]; !ok {
		if m.GetApprovedAt() != nil {
			google_protobuf_Timestamp_hashpb_sum(m.GetApprovedAt(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.Approval.approved_until"]; !ok {
		if m.GetApprovedUntil() != nil {
			google_protobuf_Timestamp_hashpb_sum(m.GetApprovedUntil(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.Approval.token"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetToken()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetToken()), len(m.GetToken())))
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.Approval.revoked"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(m.GetRevoked())))
	}
}

func cerbos_cloud_accessrequest_v1_DeniedEvaluation_hashpb_sum(m *v1.DeniedEvaluation, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.DeniedEvaluation.evaluation_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetEvaluationId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetEvaluationId()), len(m.GetEvaluationId())))
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.DeniedEvaluation.evaluated_at"]; !ok {
		if m.GetEvaluatedAt() != nil {
			google_protobuf_Timestamp_hashpb_sum(m.GetEvaluatedAt(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.DeniedEvaluation.principal"]; !ok {
		if m.GetPrincipal() != nil {
			cerbos_engine_v1_Principal_hashpb_sum(m.GetPrincipal(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.DeniedEvaluation.resource"]; !ok {
		if m.GetResource() != nil {
			cerbos_engine_v1_Resource_hashpb_sum(m.GetResource(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.DeniedEvaluation.actions"]; !ok {
		if len(m.Actions) > 0 {
			for _, v := range m.Actions {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(v))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(v), len(v)))
			}
		}
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.DeniedEvaluation.marker"]; !ok {
		if m.GetMarker() != nil {
			cerbos_cloud_accessrequest_v1_AccessRequestMarker_hashpb_sum(m.GetMarker(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.accessrequest.v1.DeniedEvaluation.rule_src"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetRuleSrc()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetRuleSrc()), len(m.GetRuleSrc())))
	}
}

func cerbos_cloud_notifications_v1_AccessRequestApproved_hashpb_sum(m *AccessRequestApproved, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.AccessRequestApproved.access_request"]; !ok {
		if m.GetAccessRequest() != nil {
			cerbos_cloud_accessrequest_v1_AccessRequest_hashpb_sum(m.GetAccessRequest(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_notifications_v1_AccessRequestCancelled_hashpb_sum(m *AccessRequestCancelled, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.AccessRequestCancelled.access_request"]; !ok {
		if m.GetAccessRequest() != nil {
			cerbos_cloud_accessrequest_v1_AccessRequest_hashpb_sum(m.GetAccessRequest(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_notifications_v1_AccessRequestDenied_hashpb_sum(m *AccessRequestDenied, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.AccessRequestDenied.access_request"]; !ok {
		if m.GetAccessRequest() != nil {
			cerbos_cloud_accessrequest_v1_AccessRequest_hashpb_sum(m.GetAccessRequest(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_notifications_v1_AccessRequestExpired_hashpb_sum(m *AccessRequestExpired, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.AccessRequestExpired.access_request"]; !ok {
		if m.GetAccessRequest() != nil {
			cerbos_cloud_accessrequest_v1_AccessRequest_hashpb_sum(m.GetAccessRequest(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_notifications_v1_AccessRequestPending_hashpb_sum(m *AccessRequestPending, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.AccessRequestPending.access_request"]; !ok {
		if m.GetAccessRequest() != nil {
			cerbos_cloud_accessrequest_v1_AccessRequest_hashpb_sum(m.GetAccessRequest(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_notifications_v1_Actor_hashpb_sum(m *Actor, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if m.Actor != nil {
		if _, ok := ignore["cerbos.cloud.notifications.v1.Actor.actor"]; !ok {
			switch t := m.Actor.(type) {
			case *Actor_MemberId:
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(t.MemberId))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(t.MemberId), len(t.MemberId)))
			case *Actor_ClientId:
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(t.ClientId))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(t.ClientId), len(t.ClientId)))
			}
		}
	}
}

func cerbos_cloud_notifications_v1_BuildFailed_Compilation_Error_Position_hashpb_sum(m *BuildFailed_Compilation_Error_Position, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.Position.line"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetLine())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.Position.column"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetColumn())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.Position.path"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetPath()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetPath()), len(m.GetPath())))
	}
}

func cerbos_cloud_notifications_v1_BuildFailed_Compilation_Error_hashpb_sum(m *BuildFailed_Compilation_Error, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.kind"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetKind())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.file"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetFile()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetFile()), len(m.GetFile())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.error"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetError()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetError()), len(m.GetError())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.description"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetDescription()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetDescription()), len(m.GetDescription())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.position"]; !ok {
		if m.GetPosition() != nil {
			cerbos_cloud_notifications_v1_BuildFailed_Compilation_Error_Position_hashpb_sum(m.GetPosition(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.context"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetContext()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetContext()), len(m.GetContext())))
	}
}

func cerbos_cloud_notifications_v1_BuildFailed_Compilation_hashpb_sum(m *BuildFailed_Compilation, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.BuildFailed.Compilation.errors"]; !ok {
		if len(m.Errors) > 0 {
			for _, v := range m.Errors {
				if v != nil {
					cerbos_cloud_notifications_v1_BuildFailed_Compilation_Error_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.BuildFailed.Compilation.error_count"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetErrorCount())))
	}
}

func cerbos_cloud_notifications_v1_BuildFailed_hashpb_sum(m *BuildFailed, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.BuildFailed.build"]; !ok {
		if m.GetBuild() != nil {
			cerbos_cloud_notifications_v1_Build_hashpb_sum(m.GetBuild(), hasher, ignore, b)
		}
	}
	if m.Failure != nil {
		if _, ok := ignore["cerbos.cloud.notifications.v1.BuildFailed.failure"]; !ok {
			switch t := m.Failure.(type) {
			case *BuildFailed_Compilation_:
				if t.Compilation != nil {
					cerbos_cloud_notifications_v1_BuildFailed_Compilation_hashpb_sum(t.Compilation, hasher, ignore, b)
				}
			case *BuildFailed_Tests:
				if t.Tests != nil {
					cerbos_cloud_notifications_v1_TestTally_hashpb_sum(t.Tests, hasher, ignore, b)
				}
			}
		}
	}
}

func cerbos_cloud_notifications_v1_BuildSucceeded_hashpb_sum(m *BuildSucceeded, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.BuildSucceeded.build"]; !ok {
		if m.GetBuild() != nil {
			cerbos_cloud_notifications_v1_Build_hashpb_sum(m.GetBuild(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.BuildSucceeded.tests"]; !ok {
		if m.GetTests() != nil {
			cerbos_cloud_notifications_v1_TestTally_hashpb_sum(m.GetTests(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_notifications_v1_Build_hashpb_sum(m *Build, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.Build.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.Build.store_ids"]; !ok {
		if len(m.StoreIds) > 0 {
			for _, v := range m.StoreIds {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(v))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(v), len(v)))
			}
		}
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.Build.deployment_ids"]; !ok {
		if len(m.DeploymentIds) > 0 {
			for _, v := range m.DeploymentIds {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(v))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(v), len(v)))
			}
		}
	}
}

func cerbos_cloud_notifications_v1_BundlePromoted_hashpb_sum(m *BundlePromoted, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.BundlePromoted.build_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetBuildId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetBuildId()), len(m.GetBuildId())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.BundlePromoted.previous_build_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetPreviousBuildId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetPreviousBuildId()), len(m.GetPreviousBuildId())))
	}
}

func cerbos_cloud_notifications_v1_ChannelDisabled_hashpb_sum(m *ChannelDisabled, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.ChannelDisabled.channel_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetChannelId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetChannelId()), len(m.GetChannelId())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.ChannelDisabled.reason"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetReason())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.ChannelDisabled.details"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetDetails()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetDetails()), len(m.GetDetails())))
	}
}

func cerbos_cloud_notifications_v1_Condition_hashpb_sum(m *Condition, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.Condition.state"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetState())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.Condition.since"]; !ok {
		if m.GetSince() != nil {
			google_protobuf_Timestamp_hashpb_sum(m.GetSince(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_notifications_v1_CredentialCreated_hashpb_sum(m *CredentialCreated, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.CredentialCreated.client_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetClientId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetClientId()), len(m.GetClientId())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.CredentialCreated.description"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetDescription()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetDescription()), len(m.GetDescription())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.CredentialCreated.actor"]; !ok {
		if m.GetActor() != nil {
			cerbos_cloud_notifications_v1_Actor_hashpb_sum(m.GetActor(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_notifications_v1_CredentialDeleted_hashpb_sum(m *CredentialDeleted, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.CredentialDeleted.client_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetClientId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetClientId()), len(m.GetClientId())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.CredentialDeleted.actor"]; !ok {
		if m.GetActor() != nil {
			cerbos_cloud_notifications_v1_Actor_hashpb_sum(m.GetActor(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_notifications_v1_DeploymentBundleLagging_hashpb_sum(m *DeploymentBundleLagging, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.DeploymentBundleLagging.condition"]; !ok {
		if m.GetCondition() != nil {
			cerbos_cloud_notifications_v1_Condition_hashpb_sum(m.GetCondition(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_notifications_v1_DeploymentFleetDark_hashpb_sum(m *DeploymentFleetDark, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.DeploymentFleetDark.condition"]; !ok {
		if m.GetCondition() != nil {
			cerbos_cloud_notifications_v1_Condition_hashpb_sum(m.GetCondition(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_notifications_v1_Event_hashpb_sum(m *Event, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.Event.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.Event.type"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetType())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.Event.occurred_at"]; !ok {
		if m.GetOccurredAt() != nil {
			google_protobuf_Timestamp_hashpb_sum(m.GetOccurredAt(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.Event.workspace_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetWorkspaceId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetWorkspaceId()), len(m.GetWorkspaceId())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.Event.deployment_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetDeploymentId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetDeploymentId()), len(m.GetDeploymentId())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.Event.link"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetLink()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetLink()), len(m.GetLink())))
	}
	if m.Payload != nil {
		if _, ok := ignore["cerbos.cloud.notifications.v1.Event.payload"]; !ok {
			switch t := m.Payload.(type) {
			case *Event_BuildFailed:
				if t.BuildFailed != nil {
					cerbos_cloud_notifications_v1_BuildFailed_hashpb_sum(t.BuildFailed, hasher, ignore, b)
				}
			case *Event_BuildSucceeded:
				if t.BuildSucceeded != nil {
					cerbos_cloud_notifications_v1_BuildSucceeded_hashpb_sum(t.BuildSucceeded, hasher, ignore, b)
				}
			case *Event_BundlePromoted:
				if t.BundlePromoted != nil {
					cerbos_cloud_notifications_v1_BundlePromoted_hashpb_sum(t.BundlePromoted, hasher, ignore, b)
				}
			case *Event_CredentialCreated:
				if t.CredentialCreated != nil {
					cerbos_cloud_notifications_v1_CredentialCreated_hashpb_sum(t.CredentialCreated, hasher, ignore, b)
				}
			case *Event_CredentialDeleted:
				if t.CredentialDeleted != nil {
					cerbos_cloud_notifications_v1_CredentialDeleted_hashpb_sum(t.CredentialDeleted, hasher, ignore, b)
				}
			case *Event_MemberAdded:
				if t.MemberAdded != nil {
					cerbos_cloud_notifications_v1_MemberAdded_hashpb_sum(t.MemberAdded, hasher, ignore, b)
				}
			case *Event_MemberRemoved:
				if t.MemberRemoved != nil {
					cerbos_cloud_notifications_v1_MemberRemoved_hashpb_sum(t.MemberRemoved, hasher, ignore, b)
				}
			case *Event_ChannelDisabled:
				if t.ChannelDisabled != nil {
					cerbos_cloud_notifications_v1_ChannelDisabled_hashpb_sum(t.ChannelDisabled, hasher, ignore, b)
				}
			case *Event_TestFired:
				if t.TestFired != nil {
					cerbos_cloud_notifications_v1_TestFired_hashpb_sum(t.TestFired, hasher, ignore, b)
				}
			case *Event_DeploymentFleetDark:
				if t.DeploymentFleetDark != nil {
					cerbos_cloud_notifications_v1_DeploymentFleetDark_hashpb_sum(t.DeploymentFleetDark, hasher, ignore, b)
				}
			case *Event_DeploymentBundleLagging:
				if t.DeploymentBundleLagging != nil {
					cerbos_cloud_notifications_v1_DeploymentBundleLagging_hashpb_sum(t.DeploymentBundleLagging, hasher, ignore, b)
				}
			case *Event_AccessRequestPending:
				if t.AccessRequestPending != nil {
					cerbos_cloud_notifications_v1_AccessRequestPending_hashpb_sum(t.AccessRequestPending, hasher, ignore, b)
				}
			case *Event_AccessRequestApproved:
				if t.AccessRequestApproved != nil {
					cerbos_cloud_notifications_v1_AccessRequestApproved_hashpb_sum(t.AccessRequestApproved, hasher, ignore, b)
				}
			case *Event_AccessRequestDenied:
				if t.AccessRequestDenied != nil {
					cerbos_cloud_notifications_v1_AccessRequestDenied_hashpb_sum(t.AccessRequestDenied, hasher, ignore, b)
				}
			case *Event_AccessRequestExpired:
				if t.AccessRequestExpired != nil {
					cerbos_cloud_notifications_v1_AccessRequestExpired_hashpb_sum(t.AccessRequestExpired, hasher, ignore, b)
				}
			case *Event_AccessRequestCancelled:
				if t.AccessRequestCancelled != nil {
					cerbos_cloud_notifications_v1_AccessRequestCancelled_hashpb_sum(t.AccessRequestCancelled, hasher, ignore, b)
				}
			}
		}
	}
}

func cerbos_cloud_notifications_v1_MemberAdded_hashpb_sum(m *MemberAdded, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.MemberAdded.member"]; !ok {
		if m.GetMember() != nil {
			cerbos_cloud_notifications_v1_Member_hashpb_sum(m.GetMember(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.MemberAdded.roles"]; !ok {
		if len(m.Roles) > 0 {
			for _, v := range m.Roles {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(v)))
			}
		}
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.MemberAdded.actor"]; !ok {
		if m.GetActor() != nil {
			cerbos_cloud_notifications_v1_Actor_hashpb_sum(m.GetActor(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_notifications_v1_MemberRemoved_hashpb_sum(m *MemberRemoved, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.MemberRemoved.member"]; !ok {
		if m.GetMember() != nil {
			cerbos_cloud_notifications_v1_Member_hashpb_sum(m.GetMember(), hasher, ignore, b)
		}
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.MemberRemoved.roles"]; !ok {
		if len(m.Roles) > 0 {
			for _, v := range m.Roles {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(v)))
			}
		}
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.MemberRemoved.actor"]; !ok {
		if m.GetActor() != nil {
			cerbos_cloud_notifications_v1_Actor_hashpb_sum(m.GetActor(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_notifications_v1_Member_hashpb_sum(m *Member, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.Member.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.Member.email"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetEmail()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetEmail()), len(m.GetEmail())))
	}
}

func cerbos_cloud_notifications_v1_TestFired_hashpb_sum(m *TestFired, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.TestFired.channel_id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetChannelId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetChannelId()), len(m.GetChannelId())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.TestFired.actor"]; !ok {
		if m.GetActor() != nil {
			cerbos_cloud_notifications_v1_Actor_hashpb_sum(m.GetActor(), hasher, ignore, b)
		}
	}
}

func cerbos_cloud_notifications_v1_TestTally_hashpb_sum(m *TestTally, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.cloud.notifications.v1.TestTally.tests_count"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetTestsCount())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.TestTally.skipped_count"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetSkippedCount())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.TestTally.passed_count"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetPassedCount())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.TestTally.failed_count"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetFailedCount())))
	}
	if _, ok := ignore["cerbos.cloud.notifications.v1.TestTally.errored_count"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetErroredCount())))
	}
}

func cerbos_engine_v1_Principal_hashpb_sum(m *v11.Principal, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.engine.v1.Principal.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
	if _, ok := ignore["cerbos.engine.v1.Principal.policy_version"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetPolicyVersion()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetPolicyVersion()), len(m.GetPolicyVersion())))
	}
	if _, ok := ignore["cerbos.engine.v1.Principal.roles"]; !ok {
		if len(m.Roles) > 0 {
			for _, v := range m.Roles {
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(v))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(v), len(v)))
			}
		}
	}
	if _, ok := ignore["cerbos.engine.v1.Principal.attr"]; !ok {
		if len(m.Attr) > 0 {
			if len(m.Attr) <= 32 {
				keys := hashpb_stringKeyPool.Get().([]string)[:0]
				for k := range m.Attr {
					keys = append(keys, k)
				}
				slices.Sort(keys)
				for _, k := range keys {
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(k))))
					_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
					if m.Attr[k] != nil {
						google_protobuf_Value_hashpb_sum(m.Attr[k], hasher, ignore, b)
					}
				}
				hashpb_stringKeyPool.Put(keys)
			} else {
				for _, k := range slices.Sorted(maps.Keys(m.Attr)) {
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(k))))
					_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
					if m.Attr[k] != nil {
						google_protobuf_Value_hashpb_sum(m.Attr[k], hasher, ignore, b)
					}
				}
			}
		}
	}
	if _, ok := ignore["cerbos.engine.v1.Principal.scope"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetScope()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetScope()), len(m.GetScope())))
	}
}

func cerbos_engine_v1_Resource_hashpb_sum(m *v11.Resource, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["cerbos.engine.v1.Resource.kind"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetKind()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetKind()), len(m.GetKind())))
	}
	if _, ok := ignore["cerbos.engine.v1.Resource.policy_version"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetPolicyVersion()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetPolicyVersion()), len(m.GetPolicyVersion())))
	}
	if _, ok := ignore["cerbos.engine.v1.Resource.id"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetId()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetId()), len(m.GetId())))
	}
	if _, ok := ignore["cerbos.engine.v1.Resource.attr"]; !ok {
		if len(m.Attr) > 0 {
			if len(m.Attr) <= 32 {
				keys := hashpb_stringKeyPool.Get().([]string)[:0]
				for k := range m.Attr {
					keys = append(keys, k)
				}
				slices.Sort(keys)
				for _, k := range keys {
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(k))))
					_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
					if m.Attr[k] != nil {
						google_protobuf_Value_hashpb_sum(m.Attr[k], hasher, ignore, b)
					}
				}
				hashpb_stringKeyPool.Put(keys)
			} else {
				for _, k := range slices.Sorted(maps.Keys(m.Attr)) {
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(k))))
					_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
					if m.Attr[k] != nil {
						google_protobuf_Value_hashpb_sum(m.Attr[k], hasher, ignore, b)
					}
				}
			}
		}
	}
	if _, ok := ignore["cerbos.engine.v1.Resource.scope"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(m.GetScope()))))
		_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(m.GetScope()), len(m.GetScope())))
	}
}

func google_protobuf_Duration_hashpb_sum(m *durationpb.Duration, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["google.protobuf.Duration.seconds"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetSeconds())))
	}
	if _, ok := ignore["google.protobuf.Duration.nanos"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetNanos())))
	}
}

func google_protobuf_ListValue_hashpb_sum(m *structpb.ListValue, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["google.protobuf.ListValue.values"]; !ok {
		if len(m.Values) > 0 {
			for _, v := range m.Values {
				if v != nil {
					google_protobuf_Value_hashpb_sum(v, hasher, ignore, b)
				}
			}
		}
	}
}

func google_protobuf_Struct_hashpb_sum(m *structpb.Struct, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["google.protobuf.Struct.fields"]; !ok {
		if len(m.Fields) > 0 {
			if len(m.Fields) <= 32 {
				keys := hashpb_stringKeyPool.Get().([]string)[:0]
				for k := range m.Fields {
					keys = append(keys, k)
				}
				slices.Sort(keys)
				for _, k := range keys {
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(k))))
					_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
					if m.Fields[k] != nil {
						google_protobuf_Value_hashpb_sum(m.Fields[k], hasher, ignore, b)
					}
				}
				hashpb_stringKeyPool.Put(keys)
			} else {
				for _, k := range slices.Sorted(maps.Keys(m.Fields)) {
					_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(k))))
					_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(k), len(k)))
					if m.Fields[k] != nil {
						google_protobuf_Value_hashpb_sum(m.Fields[k], hasher, ignore, b)
					}
				}
			}
		}
	}
}

func google_protobuf_Timestamp_hashpb_sum(m *timestamppb.Timestamp, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if _, ok := ignore["google.protobuf.Timestamp.seconds"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetSeconds())))
	}
	if _, ok := ignore["google.protobuf.Timestamp.nanos"]; !ok {
		_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(m.GetNanos())))
	}
}

func google_protobuf_Value_hashpb_sum(m *structpb.Value, hasher hash.Hash, ignore map[string]struct{}, b *[10]byte) {
	if m.Kind != nil {
		if _, ok := ignore["google.protobuf.Value.kind"]; !ok {
			switch t := m.Kind.(type) {
			case *structpb.Value_NullValue:
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(t.NullValue)))
			case *structpb.Value_NumberValue:
				_, _ = hasher.Write(protowire.AppendFixed64(b[:0], math.Float64bits(t.NumberValue)))
			case *structpb.Value_StringValue:
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], uint64(len(t.StringValue))))
				_, _ = hasher.Write(unsafe.Slice(unsafe.StringData(t.StringValue), len(t.StringValue)))
			case *structpb.Value_BoolValue:
				_, _ = hasher.Write(protowire.AppendVarint(b[:0], protowire.EncodeBool(t.BoolValue)))
			case *structpb.Value_StructValue:
				if t.StructValue != nil {
					google_protobuf_Struct_hashpb_sum(t.StructValue, hasher, ignore, b)
				}
			case *structpb.Value_ListValue:
				if t.ListValue != nil {
					google_protobuf_ListValue_hashpb_sum(t.ListValue, hasher, ignore, b)
				}
			}
		}
	}
}
