// Copyright 2021-2026 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Notification events emitted by Cerbos Hub.
//
// An Event is a fact that happened in a workspace: a build failed, a bundle was
// promoted, a deployment's PDP fleet went dark. Hub renders the same Event to
// every channel it is routed to — Slack, email and webhooks — so the message
// defined here is the single source of truth for what a notification carries.
//
// # Webhook delivery
//
// A webhook channel receives one HTTP POST per event. The body is the Event
// message encoded as protojson (https://protobuf.dev/programming-guides/json/):
// field names in lowerCamelCase, enums as their names, timestamps as RFC 3339
// strings, and the populated payload appearing as a single key named after the
// event type (for example "buildFailed"). Unset fields are omitted. Consumers
// that generate types from this package get a faithful decoder for free.
//
// Requests follow the Standard Webhooks specification
// (https://www.standardwebhooks.com/) and carry these headers:
//
//   - `webhook-id`: the value of Event.id, the same value that is in the body.
//     One event has one id: every channel the event is delivered to and every
//     retry of the same delivery carries the same `webhook-id`, so it is the
//     key to deduplicate on, including across two channels that point at the
//     same receiver.
//   - `webhook-timestamp`: the Unix time in seconds at which this delivery
//     attempt was made. Reject deliveries whose timestamp is more than five
//     minutes from the current time to defeat replay.
//   - `webhook-signature`: one or more space-separated signatures of the form
//     `v1,<base64>`. Each is `base64(HMAC-SHA256(key, signed_content))` where
//     `signed_content` is the ASCII concatenation
//     `"<webhook-id>.<webhook-timestamp>.<body>"` and `body` is the raw request
//     body bytes exactly as sent. The key is the channel's signing secret with
//     its `whsec_` prefix removed and the remainder base64-decoded. More than
//     one signature is present while a secret is being rotated; a delivery is
//     authentic if any listed signature matches. Compare in constant time.
//
// `Content-Type` is `application/json`. Any 2xx response acknowledges the
// delivery; anything else, or a timeout, is retried with backoff. A channel
// that fails continuously for three days is disabled, which is itself an event
// (EVENT_TYPE_CHANNEL_DISABLED).
//
// # Identifiers
//
// Every id in this package is the identifier shown in the Hub UI and API:
// 12 characters from 0-9A-Z for workspaces, deployments, stores, members,
// credentials, channels and events; 16 for builds and bundles.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cerbos/cloud/notifications/v1/notifications.proto

package notificationsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// EventType names the kind of an event. It is the unit that routing and alert
// rules are configured against.
//
// Each type has two spellings. The dotted name (`build.failed`) is what the Hub
// API, route and alert rule configuration and the UI use. The enum value name
// (`EVENT_TYPE_BUILD_FAILED`) is what protojson renders, so it is what appears
// in the `type` field of a webhook body. Each value's comment gives its dotted
// name and the Event payload field it corresponds to.
type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	// `build.failed`: a build finished with compile errors or failing tests.
	// Payload: build_failed.
	EventType_EVENT_TYPE_BUILD_FAILED EventType = 1
	// `build.succeeded`: a build produced a bundle. Payload: build_succeeded.
	EventType_EVENT_TYPE_BUILD_SUCCEEDED EventType = 2
	// `bundle.promoted`: a deployment's promoted bundle changed.
	// Payload: bundle_promoted.
	EventType_EVENT_TYPE_BUNDLE_PROMOTED EventType = 3
	// `credential.created`: a client credential (API key) was created.
	// Payload: credential_created.
	EventType_EVENT_TYPE_CREDENTIAL_CREATED EventType = 4
	// `credential.deleted`: a client credential (API key) was deleted.
	// Payload: credential_deleted.
	EventType_EVENT_TYPE_CREDENTIAL_DELETED EventType = 5
	// `member.added`: a member was added to the workspace. Payload: member_added.
	EventType_EVENT_TYPE_MEMBER_ADDED EventType = 6
	// `member.removed`: a member was removed from the workspace.
	// Payload: member_removed.
	EventType_EVENT_TYPE_MEMBER_REMOVED EventType = 7
	// `channel.disabled`: Hub disabled a notification channel.
	// Payload: channel_disabled.
	EventType_EVENT_TYPE_CHANNEL_DISABLED EventType = 8
	// `test.fired`: a member test-fired a channel. Payload: test_fired.
	EventType_EVENT_TYPE_TEST_FIRED EventType = 9
	// `deployment.fleet_dark`: a deployment's connected PDP count has been zero
	// for longer than the threshold, or that condition cleared.
	// Payload: deployment_fleet_dark.
	EventType_EVENT_TYPE_DEPLOYMENT_FLEET_DARK EventType = 10
	// `deployment.bundle_lagging`: a connected PDP in a deployment has been
	// running a bundle other than the promoted one for longer than the
	// threshold, or that condition cleared. Payload: deployment_bundle_lagging.
	EventType_EVENT_TYPE_DEPLOYMENT_BUNDLE_LAGGING EventType = 11
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0:  "EVENT_TYPE_UNSPECIFIED",
		1:  "EVENT_TYPE_BUILD_FAILED",
		2:  "EVENT_TYPE_BUILD_SUCCEEDED",
		3:  "EVENT_TYPE_BUNDLE_PROMOTED",
		4:  "EVENT_TYPE_CREDENTIAL_CREATED",
		5:  "EVENT_TYPE_CREDENTIAL_DELETED",
		6:  "EVENT_TYPE_MEMBER_ADDED",
		7:  "EVENT_TYPE_MEMBER_REMOVED",
		8:  "EVENT_TYPE_CHANNEL_DISABLED",
		9:  "EVENT_TYPE_TEST_FIRED",
		10: "EVENT_TYPE_DEPLOYMENT_FLEET_DARK",
		11: "EVENT_TYPE_DEPLOYMENT_BUNDLE_LAGGING",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":               0,
		"EVENT_TYPE_BUILD_FAILED":              1,
		"EVENT_TYPE_BUILD_SUCCEEDED":           2,
		"EVENT_TYPE_BUNDLE_PROMOTED":           3,
		"EVENT_TYPE_CREDENTIAL_CREATED":        4,
		"EVENT_TYPE_CREDENTIAL_DELETED":        5,
		"EVENT_TYPE_MEMBER_ADDED":              6,
		"EVENT_TYPE_MEMBER_REMOVED":            7,
		"EVENT_TYPE_CHANNEL_DISABLED":          8,
		"EVENT_TYPE_TEST_FIRED":                9,
		"EVENT_TYPE_DEPLOYMENT_FLEET_DARK":     10,
		"EVENT_TYPE_DEPLOYMENT_BUNDLE_LAGGING": 11,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbos_cloud_notifications_v1_notifications_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_cerbos_cloud_notifications_v1_notifications_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{0}
}

// ConditionState says which edge of a condition event this is. Condition
// events (fleet dark, bundle lagging) are emitted once when a deployment enters
// the state and once when it leaves it.
type ConditionState int32

const (
	ConditionState_CONDITION_STATE_UNSPECIFIED ConditionState = 0
	// The deployment has just entered the condition.
	ConditionState_CONDITION_STATE_ENTERED ConditionState = 1
	// The deployment has just left the condition.
	ConditionState_CONDITION_STATE_CLEARED ConditionState = 2
)

// Enum value maps for ConditionState.
var (
	ConditionState_name = map[int32]string{
		0: "CONDITION_STATE_UNSPECIFIED",
		1: "CONDITION_STATE_ENTERED",
		2: "CONDITION_STATE_CLEARED",
	}
	ConditionState_value = map[string]int32{
		"CONDITION_STATE_UNSPECIFIED": 0,
		"CONDITION_STATE_ENTERED":     1,
		"CONDITION_STATE_CLEARED":     2,
	}
)

func (x ConditionState) Enum() *ConditionState {
	p := new(ConditionState)
	*p = x
	return p
}

func (x ConditionState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConditionState) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbos_cloud_notifications_v1_notifications_proto_enumTypes[1].Descriptor()
}

func (ConditionState) Type() protoreflect.EnumType {
	return &file_cerbos_cloud_notifications_v1_notifications_proto_enumTypes[1]
}

func (x ConditionState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConditionState.Descriptor instead.
func (ConditionState) EnumDescriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{1}
}

// WorkspaceRole is a role a member holds in a workspace. Values mirror
// spitfire.account.v1.WorkspaceRole; keep the numbering aligned.
type WorkspaceRole int32

const (
	WorkspaceRole_WORKSPACE_ROLE_UNSPECIFIED WorkspaceRole = 0
	WorkspaceRole_WORKSPACE_ROLE_OWNER       WorkspaceRole = 1
	WorkspaceRole_WORKSPACE_ROLE_VIEWER      WorkspaceRole = 2
	WorkspaceRole_WORKSPACE_ROLE_DEVELOPER   WorkspaceRole = 3
	WorkspaceRole_WORKSPACE_ROLE_ANALYST     WorkspaceRole = 4
)

// Enum value maps for WorkspaceRole.
var (
	WorkspaceRole_name = map[int32]string{
		0: "WORKSPACE_ROLE_UNSPECIFIED",
		1: "WORKSPACE_ROLE_OWNER",
		2: "WORKSPACE_ROLE_VIEWER",
		3: "WORKSPACE_ROLE_DEVELOPER",
		4: "WORKSPACE_ROLE_ANALYST",
	}
	WorkspaceRole_value = map[string]int32{
		"WORKSPACE_ROLE_UNSPECIFIED": 0,
		"WORKSPACE_ROLE_OWNER":       1,
		"WORKSPACE_ROLE_VIEWER":      2,
		"WORKSPACE_ROLE_DEVELOPER":   3,
		"WORKSPACE_ROLE_ANALYST":     4,
	}
)

func (x WorkspaceRole) Enum() *WorkspaceRole {
	p := new(WorkspaceRole)
	*p = x
	return p
}

func (x WorkspaceRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkspaceRole) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbos_cloud_notifications_v1_notifications_proto_enumTypes[2].Descriptor()
}

func (WorkspaceRole) Type() protoreflect.EnumType {
	return &file_cerbos_cloud_notifications_v1_notifications_proto_enumTypes[2]
}

func (x WorkspaceRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkspaceRole.Descriptor instead.
func (WorkspaceRole) EnumDescriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{2}
}

// Kind classifies the error.
type BuildFailed_Compilation_Error_Kind int32

const (
	BuildFailed_Compilation_Error_KIND_UNSPECIFIED BuildFailed_Compilation_Error_Kind = 0
	// A policy failed to compile (an invalid condition, an unknown
	// variable, ...).
	BuildFailed_Compilation_Error_KIND_COMPILE_ERROR BuildFailed_Compilation_Error_Kind = 1
	// A file could not be parsed or failed schema validation.
	BuildFailed_Compilation_Error_KIND_LOAD_FAILURE BuildFailed_Compilation_Error_Kind = 2
	// The same policy is defined in more than one file.
	BuildFailed_Compilation_Error_KIND_DUPLICATE_DEFINITION BuildFailed_Compilation_Error_Kind = 3
	// A policy imports derived roles or variables that do not exist.
	BuildFailed_Compilation_Error_KIND_MISSING_IMPORT BuildFailed_Compilation_Error_Kind = 4
	// A scoped policy has no policy for an ancestor scope.
	BuildFailed_Compilation_Error_KIND_MISSING_SCOPE BuildFailed_Compilation_Error_Kind = 5
	// Policies in a scope chain declare conflicting scope permissions.
	BuildFailed_Compilation_Error_KIND_SCOPE_PERMISSIONS_CONFLICT BuildFailed_Compilation_Error_Kind = 6
	// A policy is disabled and cannot be referenced.
	BuildFailed_Compilation_Error_KIND_DISABLED_DEFINITION BuildFailed_Compilation_Error_Kind = 7
)

// Enum value maps for BuildFailed_Compilation_Error_Kind.
var (
	BuildFailed_Compilation_Error_Kind_name = map[int32]string{
		0: "KIND_UNSPECIFIED",
		1: "KIND_COMPILE_ERROR",
		2: "KIND_LOAD_FAILURE",
		3: "KIND_DUPLICATE_DEFINITION",
		4: "KIND_MISSING_IMPORT",
		5: "KIND_MISSING_SCOPE",
		6: "KIND_SCOPE_PERMISSIONS_CONFLICT",
		7: "KIND_DISABLED_DEFINITION",
	}
	BuildFailed_Compilation_Error_Kind_value = map[string]int32{
		"KIND_UNSPECIFIED":                0,
		"KIND_COMPILE_ERROR":              1,
		"KIND_LOAD_FAILURE":               2,
		"KIND_DUPLICATE_DEFINITION":       3,
		"KIND_MISSING_IMPORT":             4,
		"KIND_MISSING_SCOPE":              5,
		"KIND_SCOPE_PERMISSIONS_CONFLICT": 6,
		"KIND_DISABLED_DEFINITION":        7,
	}
)

func (x BuildFailed_Compilation_Error_Kind) Enum() *BuildFailed_Compilation_Error_Kind {
	p := new(BuildFailed_Compilation_Error_Kind)
	*p = x
	return p
}

func (x BuildFailed_Compilation_Error_Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildFailed_Compilation_Error_Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbos_cloud_notifications_v1_notifications_proto_enumTypes[3].Descriptor()
}

func (BuildFailed_Compilation_Error_Kind) Type() protoreflect.EnumType {
	return &file_cerbos_cloud_notifications_v1_notifications_proto_enumTypes[3]
}

func (x BuildFailed_Compilation_Error_Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildFailed_Compilation_Error_Kind.Descriptor instead.
func (BuildFailed_Compilation_Error_Kind) EnumDescriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{6, 0, 0, 0}
}

// Reason says why Hub disabled the channel.
type ChannelDisabled_Reason int32

const (
	ChannelDisabled_REASON_UNSPECIFIED ChannelDisabled_Reason = 0
	// Every delivery to the channel failed for three consecutive days.
	ChannelDisabled_REASON_DELIVERY_FAILURES ChannelDisabled_Reason = 1
)

// Enum value maps for ChannelDisabled_Reason.
var (
	ChannelDisabled_Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "REASON_DELIVERY_FAILURES",
	}
	ChannelDisabled_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED":       0,
		"REASON_DELIVERY_FAILURES": 1,
	}
)

func (x ChannelDisabled_Reason) Enum() *ChannelDisabled_Reason {
	p := new(ChannelDisabled_Reason)
	*p = x
	return p
}

func (x ChannelDisabled_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChannelDisabled_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbos_cloud_notifications_v1_notifications_proto_enumTypes[4].Descriptor()
}

func (ChannelDisabled_Reason) Type() protoreflect.EnumType {
	return &file_cerbos_cloud_notifications_v1_notifications_proto_enumTypes[4]
}

func (x ChannelDisabled_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChannelDisabled_Reason.Descriptor instead.
func (ChannelDisabled_Reason) EnumDescriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{13, 0}
}

// Event is one notification event. The envelope fields identify and locate the
// event; exactly one payload field is set, and it is the one named by `type`.
type Event struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique id of the event, assigned by Hub. Every delivery of the event, to
	// any channel and on any retry, carries the same id (it is the `webhook-id`
	// header), so consumers can deduplicate on it.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The kind of event. Names the payload field that is set.
	Type EventType `protobuf:"varint,2,opt,name=type,proto3,enum=cerbos.cloud.notifications.v1.EventType" json:"type,omitempty"`
	// When the fact this event describes happened. For condition events this is
	// when the state was entered or cleared, which can be later than
	// Condition.since by the detection threshold.
	OccurredAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	// The workspace the event belongs to.
	WorkspaceId string `protobuf:"bytes,4,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// The deployment the event concerns. Set for bundle and deployment events;
	// absent for workspace-level events. Builds are workspace-level and fan out
	// to the deployments listed in Build.deployment_ids.
	DeploymentId *string `protobuf:"bytes,5,opt,name=deployment_id,json=deploymentId,proto3,oneof" json:"deployment_id,omitempty"`
	// Absolute URL of the page in the Hub UI that shows the subject of the event
	// (the build, the deployment, the member list, ...).
	Link string `protobuf:"bytes,6,opt,name=link,proto3" json:"link,omitempty"`
	// The event-type-specific payload. Exactly one is set, matching `type`.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Event_BuildFailed
	//	*Event_BuildSucceeded
	//	*Event_BundlePromoted
	//	*Event_CredentialCreated
	//	*Event_CredentialDeleted
	//	*Event_MemberAdded
	//	*Event_MemberRemoved
	//	*Event_ChannelDisabled
	//	*Event_TestFired
	//	*Event_DeploymentFleetDark
	//	*Event_DeploymentBundleLagging
	Payload       isEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{0}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *Event) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *Event) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *Event) GetDeploymentId() string {
	if x != nil && x.DeploymentId != nil {
		return *x.DeploymentId
	}
	return ""
}

func (x *Event) GetLink() string {
	if x != nil {
		return x.Link
	}
	return ""
}

func (x *Event) GetPayload() isEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Event) GetBuildFailed() *BuildFailed {
	if x != nil {
		if x, ok := x.Payload.(*Event_BuildFailed); ok {
			return x.BuildFailed
		}
	}
	return nil
}

func (x *Event) GetBuildSucceeded() *BuildSucceeded {
	if x != nil {
		if x, ok := x.Payload.(*Event_BuildSucceeded); ok {
			return x.BuildSucceeded
		}
	}
	return nil
}

func (x *Event) GetBundlePromoted() *BundlePromoted {
	if x != nil {
		if x, ok := x.Payload.(*Event_BundlePromoted); ok {
			return x.BundlePromoted
		}
	}
	return nil
}

func (x *Event) GetCredentialCreated() *CredentialCreated {
	if x != nil {
		if x, ok := x.Payload.(*Event_CredentialCreated); ok {
			return x.CredentialCreated
		}
	}
	return nil
}

func (x *Event) GetCredentialDeleted() *CredentialDeleted {
	if x != nil {
		if x, ok := x.Payload.(*Event_CredentialDeleted); ok {
			return x.CredentialDeleted
		}
	}
	return nil
}

func (x *Event) GetMemberAdded() *MemberAdded {
	if x != nil {
		if x, ok := x.Payload.(*Event_MemberAdded); ok {
			return x.MemberAdded
		}
	}
	return nil
}

func (x *Event) GetMemberRemoved() *MemberRemoved {
	if x != nil {
		if x, ok := x.Payload.(*Event_MemberRemoved); ok {
			return x.MemberRemoved
		}
	}
	return nil
}

func (x *Event) GetChannelDisabled() *ChannelDisabled {
	if x != nil {
		if x, ok := x.Payload.(*Event_ChannelDisabled); ok {
			return x.ChannelDisabled
		}
	}
	return nil
}

func (x *Event) GetTestFired() *TestFired {
	if x != nil {
		if x, ok := x.Payload.(*Event_TestFired); ok {
			return x.TestFired
		}
	}
	return nil
}

func (x *Event) GetDeploymentFleetDark() *DeploymentFleetDark {
	if x != nil {
		if x, ok := x.Payload.(*Event_DeploymentFleetDark); ok {
			return x.DeploymentFleetDark
		}
	}
	return nil
}

func (x *Event) GetDeploymentBundleLagging() *DeploymentBundleLagging {
	if x != nil {
		if x, ok := x.Payload.(*Event_DeploymentBundleLagging); ok {
			return x.DeploymentBundleLagging
		}
	}
	return nil
}

type isEvent_Payload interface {
	isEvent_Payload()
}

type Event_BuildFailed struct {
	BuildFailed *BuildFailed `protobuf:"bytes,10,opt,name=build_failed,json=buildFailed,proto3,oneof"`
}

type Event_BuildSucceeded struct {
	BuildSucceeded *BuildSucceeded `protobuf:"bytes,11,opt,name=build_succeeded,json=buildSucceeded,proto3,oneof"`
}

type Event_BundlePromoted struct {
	BundlePromoted *BundlePromoted `protobuf:"bytes,12,opt,name=bundle_promoted,json=bundlePromoted,proto3,oneof"`
}

type Event_CredentialCreated struct {
	CredentialCreated *CredentialCreated `protobuf:"bytes,13,opt,name=credential_created,json=credentialCreated,proto3,oneof"`
}

type Event_CredentialDeleted struct {
	CredentialDeleted *CredentialDeleted `protobuf:"bytes,14,opt,name=credential_deleted,json=credentialDeleted,proto3,oneof"`
}

type Event_MemberAdded struct {
	MemberAdded *MemberAdded `protobuf:"bytes,15,opt,name=member_added,json=memberAdded,proto3,oneof"`
}

type Event_MemberRemoved struct {
	MemberRemoved *MemberRemoved `protobuf:"bytes,16,opt,name=member_removed,json=memberRemoved,proto3,oneof"`
}

type Event_ChannelDisabled struct {
	ChannelDisabled *ChannelDisabled `protobuf:"bytes,17,opt,name=channel_disabled,json=channelDisabled,proto3,oneof"`
}

type Event_TestFired struct {
	TestFired *TestFired `protobuf:"bytes,18,opt,name=test_fired,json=testFired,proto3,oneof"`
}

type Event_DeploymentFleetDark struct {
	DeploymentFleetDark *DeploymentFleetDark `protobuf:"bytes,19,opt,name=deployment_fleet_dark,json=deploymentFleetDark,proto3,oneof"`
}

type Event_DeploymentBundleLagging struct {
	DeploymentBundleLagging *DeploymentBundleLagging `protobuf:"bytes,20,opt,name=deployment_bundle_lagging,json=deploymentBundleLagging,proto3,oneof"`
}

func (*Event_BuildFailed) isEvent_Payload() {}

func (*Event_BuildSucceeded) isEvent_Payload() {}

func (*Event_BundlePromoted) isEvent_Payload() {}

func (*Event_CredentialCreated) isEvent_Payload() {}

func (*Event_CredentialDeleted) isEvent_Payload() {}

func (*Event_MemberAdded) isEvent_Payload() {}

func (*Event_MemberRemoved) isEvent_Payload() {}

func (*Event_ChannelDisabled) isEvent_Payload() {}

func (*Event_TestFired) isEvent_Payload() {}

func (*Event_DeploymentFleetDark) isEvent_Payload() {}

func (*Event_DeploymentBundleLagging) isEvent_Payload() {}

// Actor is who performed the action an event describes: a workspace member
// acting through the UI or API, or a client credential acting through the API.
type Actor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Actor:
	//
	//	*Actor_MemberId
	//	*Actor_ClientId
	Actor         isActor_Actor `protobuf_oneof:"actor"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{1}
}

func (x *Actor) GetActor() isActor_Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *Actor) GetMemberId() string {
	if x != nil {
		if x, ok := x.Actor.(*Actor_MemberId); ok {
			return x.MemberId
		}
	}
	return ""
}

func (x *Actor) GetClientId() string {
	if x != nil {
		if x, ok := x.Actor.(*Actor_ClientId); ok {
			return x.ClientId
		}
	}
	return ""
}

type isActor_Actor interface {
	isActor_Actor()
}

type Actor_MemberId struct {
	// Id of the member who performed the action.
	MemberId string `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3,oneof"`
}

type Actor_ClientId struct {
	// Client id of the credential that performed the action.
	ClientId string `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3,oneof"`
}

func (*Actor_MemberId) isActor_Actor() {}

func (*Actor_ClientId) isActor_Actor() {}

// Member identifies a workspace member.
type Member struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The member's id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The member's email address, when their profile has one.
	Email         *string `protobuf:"bytes,2,opt,name=email,proto3,oneof" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{2}
}

func (x *Member) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Member) GetEmail() string {
	if x != nil && x.Email != nil {
		return *x.Email
	}
	return ""
}

// Build identifies a build, the stores whose contents it was built from and
// the deployments it affects.
type Build struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The build's id.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Ids of the stores that were inputs to the build.
	StoreIds []string `protobuf:"bytes,2,rep,name=store_ids,json=storeIds,proto3" json:"store_ids,omitempty"`
	// Ids of the deployments that serve bundles built from these stores, and so
	// are affected by this build. Empty when no deployment uses this store set.
	DeploymentIds []string `protobuf:"bytes,3,rep,name=deployment_ids,json=deploymentIds,proto3" json:"deployment_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Build) Reset() {
	*x = Build{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{3}
}

func (x *Build) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Build) GetStoreIds() []string {
	if x != nil {
		return x.StoreIds
	}
	return nil
}

func (x *Build) GetDeploymentIds() []string {
	if x != nil {
		return x.DeploymentIds
	}
	return nil
}

// TestTally counts the outcomes of the policy tests a build ran. Counts are of
// individual test cases (one principal, resource and action combination).
type TestTally struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of test cases. Equal to the sum of the other counts.
	TestsCount uint32 `protobuf:"varint,1,opt,name=tests_count,json=testsCount,proto3" json:"tests_count,omitempty"`
	// Test cases that were skipped.
	SkippedCount uint32 `protobuf:"varint,2,opt,name=skipped_count,json=skippedCount,proto3" json:"skipped_count,omitempty"`
	// Test cases that passed.
	PassedCount uint32 `protobuf:"varint,3,opt,name=passed_count,json=passedCount,proto3" json:"passed_count,omitempty"`
	// Test cases whose outcome differed from the expectation.
	FailedCount uint32 `protobuf:"varint,4,opt,name=failed_count,json=failedCount,proto3" json:"failed_count,omitempty"`
	// Test cases that could not run to completion.
	ErroredCount  uint32 `protobuf:"varint,5,opt,name=errored_count,json=erroredCount,proto3" json:"errored_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestTally) Reset() {
	*x = TestTally{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestTally) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestTally) ProtoMessage() {}

func (x *TestTally) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestTally.ProtoReflect.Descriptor instead.
func (*TestTally) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{4}
}

func (x *TestTally) GetTestsCount() uint32 {
	if x != nil {
		return x.TestsCount
	}
	return 0
}

func (x *TestTally) GetSkippedCount() uint32 {
	if x != nil {
		return x.SkippedCount
	}
	return 0
}

func (x *TestTally) GetPassedCount() uint32 {
	if x != nil {
		return x.PassedCount
	}
	return 0
}

func (x *TestTally) GetFailedCount() uint32 {
	if x != nil {
		return x.FailedCount
	}
	return 0
}

func (x *TestTally) GetErroredCount() uint32 {
	if x != nil {
		return x.ErroredCount
	}
	return 0
}

// Condition carries the state change of a condition event.
type Condition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the deployment entered or cleared the condition.
	State ConditionState `protobuf:"varint,1,opt,name=state,proto3,enum=cerbos.cloud.notifications.v1.ConditionState" json:"state,omitempty"`
	// When the deployment entered the condition. Present on both edges, so the
	// clearing event says how long the condition lasted.
	Since         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=since,proto3" json:"since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Condition) Reset() {
	*x = Condition{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Condition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Condition) ProtoMessage() {}

func (x *Condition) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Condition.ProtoReflect.Descriptor instead.
func (*Condition) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{5}
}

func (x *Condition) GetState() ConditionState {
	if x != nil {
		return x.State
	}
	return ConditionState_CONDITION_STATE_UNSPECIFIED
}

func (x *Condition) GetSince() *timestamppb.Timestamp {
	if x != nil {
		return x.Since
	}
	return nil
}

// BuildFailed is the payload of EVENT_TYPE_BUILD_FAILED. A build fails either
// because the policies did not compile or because at least one policy test
// failed or errored; `failure` says which and carries the details.
type BuildFailed struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The build that failed.
	Build *Build `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	// Why the build failed.
	//
	// Types that are valid to be assigned to Failure:
	//
	//	*BuildFailed_Compilation_
	//	*BuildFailed_Tests
	Failure       isBuildFailed_Failure `protobuf_oneof:"failure"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildFailed) Reset() {
	*x = BuildFailed{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildFailed) ProtoMessage() {}

func (x *BuildFailed) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildFailed.ProtoReflect.Descriptor instead.
func (*BuildFailed) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{6}
}

func (x *BuildFailed) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *BuildFailed) GetFailure() isBuildFailed_Failure {
	if x != nil {
		return x.Failure
	}
	return nil
}

func (x *BuildFailed) GetCompilation() *BuildFailed_Compilation {
	if x != nil {
		if x, ok := x.Failure.(*BuildFailed_Compilation_); ok {
			return x.Compilation
		}
	}
	return nil
}

func (x *BuildFailed) GetTests() *TestTally {
	if x != nil {
		if x, ok := x.Failure.(*BuildFailed_Tests); ok {
			return x.Tests
		}
	}
	return nil
}

type isBuildFailed_Failure interface {
	isBuildFailed_Failure()
}

type BuildFailed_Compilation_ struct {
	// The policies did not compile.
	Compilation *BuildFailed_Compilation `protobuf:"bytes,2,opt,name=compilation,proto3,oneof"`
}

type BuildFailed_Tests struct {
	// The policies compiled but tests failed or errored. At least one of
	// `failed_count` and `errored_count` is non-zero.
	Tests *TestTally `protobuf:"bytes,3,opt,name=tests,proto3,oneof"`
}

func (*BuildFailed_Compilation_) isBuildFailed_Failure() {}

func (*BuildFailed_Tests) isBuildFailed_Failure() {}

// BuildSucceeded is the payload of EVENT_TYPE_BUILD_SUCCEEDED.
type BuildSucceeded struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The build that succeeded.
	Build *Build `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	// Outcomes of the policy tests the build ran. Absent when the stores contain
	// no tests.
	Tests         *TestTally `protobuf:"bytes,2,opt,name=tests,proto3,oneof" json:"tests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSucceeded) Reset() {
	*x = BuildSucceeded{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSucceeded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSucceeded) ProtoMessage() {}

func (x *BuildSucceeded) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSucceeded.ProtoReflect.Descriptor instead.
func (*BuildSucceeded) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{7}
}

func (x *BuildSucceeded) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *BuildSucceeded) GetTests() *TestTally {
	if x != nil {
		return x.Tests
	}
	return nil
}

// BundlePromoted is the payload of EVENT_TYPE_BUNDLE_PROMOTED: the deployment
// named by Event.deployment_id now serves the bundle produced by `build_id`.
type BundlePromoted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the build whose bundle is now promoted.
	BuildId string `protobuf:"bytes,1,opt,name=build_id,json=buildId,proto3" json:"build_id,omitempty"`
	// Id of the build whose bundle was promoted before this one. Absent for the
	// deployment's first promotion.
	PreviousBuildId *string `protobuf:"bytes,2,opt,name=previous_build_id,json=previousBuildId,proto3,oneof" json:"previous_build_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *BundlePromoted) Reset() {
	*x = BundlePromoted{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundlePromoted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundlePromoted) ProtoMessage() {}

func (x *BundlePromoted) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundlePromoted.ProtoReflect.Descriptor instead.
func (*BundlePromoted) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{8}
}

func (x *BundlePromoted) GetBuildId() string {
	if x != nil {
		return x.BuildId
	}
	return ""
}

func (x *BundlePromoted) GetPreviousBuildId() string {
	if x != nil && x.PreviousBuildId != nil {
		return *x.PreviousBuildId
	}
	return ""
}

// CredentialCreated is the payload of EVENT_TYPE_CREDENTIAL_CREATED.
type CredentialCreated struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client id of the new credential. The secret is never included.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// The description given to the credential when it was created.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// Who created it.
	Actor         *Actor `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialCreated) Reset() {
	*x = CredentialCreated{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialCreated) ProtoMessage() {}

func (x *CredentialCreated) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialCreated.ProtoReflect.Descriptor instead.
func (*CredentialCreated) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{9}
}

func (x *CredentialCreated) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CredentialCreated) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CredentialCreated) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

// CredentialDeleted is the payload of EVENT_TYPE_CREDENTIAL_DELETED.
type CredentialDeleted struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Client id of the deleted credential.
	ClientId string `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Who deleted it.
	Actor         *Actor `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialDeleted) Reset() {
	*x = CredentialDeleted{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialDeleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialDeleted) ProtoMessage() {}

func (x *CredentialDeleted) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialDeleted.ProtoReflect.Descriptor instead.
func (*CredentialDeleted) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{10}
}

func (x *CredentialDeleted) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CredentialDeleted) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

// MemberAdded is the payload of EVENT_TYPE_MEMBER_ADDED.
type MemberAdded struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The member who was added.
	Member *Member `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	// The roles the member was given.
	Roles []WorkspaceRole `protobuf:"varint,2,rep,packed,name=roles,proto3,enum=cerbos.cloud.notifications.v1.WorkspaceRole" json:"roles,omitempty"`
	// Who added them.
	Actor         *Actor `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberAdded) Reset() {
	*x = MemberAdded{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberAdded) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberAdded) ProtoMessage() {}

func (x *MemberAdded) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberAdded.ProtoReflect.Descriptor instead.
func (*MemberAdded) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{11}
}

func (x *MemberAdded) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *MemberAdded) GetRoles() []WorkspaceRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *MemberAdded) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

// MemberRemoved is the payload of EVENT_TYPE_MEMBER_REMOVED.
type MemberRemoved struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The member who was removed.
	Member *Member `protobuf:"bytes,1,opt,name=member,proto3" json:"member,omitempty"`
	// The roles the member held at the time of removal.
	Roles []WorkspaceRole `protobuf:"varint,2,rep,packed,name=roles,proto3,enum=cerbos.cloud.notifications.v1.WorkspaceRole" json:"roles,omitempty"`
	// Who removed them.
	Actor         *Actor `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberRemoved) Reset() {
	*x = MemberRemoved{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberRemoved) ProtoMessage() {}

func (x *MemberRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberRemoved.ProtoReflect.Descriptor instead.
func (*MemberRemoved) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{12}
}

func (x *MemberRemoved) GetMember() *Member {
	if x != nil {
		return x.Member
	}
	return nil
}

func (x *MemberRemoved) GetRoles() []WorkspaceRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *MemberRemoved) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

// ChannelDisabled is the payload of EVENT_TYPE_CHANNEL_DISABLED: Hub stopped
// delivering to a channel. This event is delivered to the workspace's other
// channels, never to the disabled one.
type ChannelDisabled struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the disabled channel.
	ChannelId string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Reason    ChannelDisabled_Reason `protobuf:"varint,2,opt,name=reason,proto3,enum=cerbos.cloud.notifications.v1.ChannelDisabled_Reason" json:"reason,omitempty"`
	// Detail supporting the reason, such as the last delivery error.
	Details       string `protobuf:"bytes,3,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelDisabled) Reset() {
	*x = ChannelDisabled{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelDisabled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelDisabled) ProtoMessage() {}

func (x *ChannelDisabled) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelDisabled.ProtoReflect.Descriptor instead.
func (*ChannelDisabled) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{13}
}

func (x *ChannelDisabled) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelDisabled) GetReason() ChannelDisabled_Reason {
	if x != nil {
		return x.Reason
	}
	return ChannelDisabled_REASON_UNSPECIFIED
}

func (x *ChannelDisabled) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// TestFired is the payload of EVENT_TYPE_TEST_FIRED: a synthetic event a
// member sent through a single channel to prove that the channel works. It is
// never routed by alert rules and is only ever delivered to `channel_id`.
type TestFired struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the channel being tested.
	ChannelId string `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	// Who fired the test.
	Actor         *Actor `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestFired) Reset() {
	*x = TestFired{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestFired) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestFired) ProtoMessage() {}

func (x *TestFired) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestFired.ProtoReflect.Descriptor instead.
func (*TestFired) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{14}
}

func (x *TestFired) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *TestFired) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

// DeploymentFleetDark is the payload of EVENT_TYPE_DEPLOYMENT_FLEET_DARK: the
// deployment named by Event.deployment_id has had no connected PDPs for longer
// than the threshold (ENTERED), or a PDP has connected again (CLEARED).
type DeploymentFleetDark struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     *Condition             `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentFleetDark) Reset() {
	*x = DeploymentFleetDark{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentFleetDark) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentFleetDark) ProtoMessage() {}

func (x *DeploymentFleetDark) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentFleetDark.ProtoReflect.Descriptor instead.
func (*DeploymentFleetDark) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{15}
}

func (x *DeploymentFleetDark) GetCondition() *Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

// DeploymentBundleLagging is the payload of
// EVENT_TYPE_DEPLOYMENT_BUNDLE_LAGGING: a connected PDP in the deployment named
// by Event.deployment_id has been running a bundle other than the promoted one
// for longer than the threshold (ENTERED), or every connected PDP is on the
// promoted bundle again (CLEARED).
type DeploymentBundleLagging struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Condition     *Condition             `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploymentBundleLagging) Reset() {
	*x = DeploymentBundleLagging{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploymentBundleLagging) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploymentBundleLagging) ProtoMessage() {}

func (x *DeploymentBundleLagging) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploymentBundleLagging.ProtoReflect.Descriptor instead.
func (*DeploymentBundleLagging) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{16}
}

func (x *DeploymentBundleLagging) GetCondition() *Condition {
	if x != nil {
		return x.Condition
	}
	return nil
}

// Compilation is the detail of a build that failed to compile.
type BuildFailed_Compilation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The errors, in the order Hub reported them, capped at 100. Compare
	// `error_count` to the length of this list to tell whether it was cut.
	Errors []*BuildFailed_Compilation_Error `protobuf:"bytes,1,rep,name=errors,proto3" json:"errors,omitempty"`
	// Total number of errors, which can exceed the number listed.
	ErrorCount    uint32 `protobuf:"varint,2,opt,name=error_count,json=errorCount,proto3" json:"error_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildFailed_Compilation) Reset() {
	*x = BuildFailed_Compilation{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildFailed_Compilation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildFailed_Compilation) ProtoMessage() {}

func (x *BuildFailed_Compilation) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildFailed_Compilation.ProtoReflect.Descriptor instead.
func (*BuildFailed_Compilation) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{6, 0}
}

func (x *BuildFailed_Compilation) GetErrors() []*BuildFailed_Compilation_Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *BuildFailed_Compilation) GetErrorCount() uint32 {
	if x != nil {
		return x.ErrorCount
	}
	return 0
}

// Error is one problem found while loading or compiling the policies.
// The shape mirrors the compile errors Hub records for the build.
type BuildFailed_Compilation_Error struct {
	state protoimpl.MessageState             `protogen:"open.v1"`
	Kind  BuildFailed_Compilation_Error_Kind `protobuf:"varint,1,opt,name=kind,proto3,enum=cerbos.cloud.notifications.v1.BuildFailed_Compilation_Error_Kind" json:"kind,omitempty"`
	// Path of the file the error was found in, relative to the store root.
	// Empty for errors that are not tied to a file (missing scope, scope
	// permissions conflict).
	File string `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	// One-line summary of the error.
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	// Longer explanation of the error, when there is one.
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// Where in the file the error is, when known.
	Position *BuildFailed_Compilation_Error_Position `protobuf:"bytes,5,opt,name=position,proto3,oneof" json:"position,omitempty"`
	// The lines of source around the error, when known.
	Context       string `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildFailed_Compilation_Error) Reset() {
	*x = BuildFailed_Compilation_Error{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildFailed_Compilation_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildFailed_Compilation_Error) ProtoMessage() {}

func (x *BuildFailed_Compilation_Error) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildFailed_Compilation_Error.ProtoReflect.Descriptor instead.
func (*BuildFailed_Compilation_Error) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{6, 0, 0}
}

func (x *BuildFailed_Compilation_Error) GetKind() BuildFailed_Compilation_Error_Kind {
	if x != nil {
		return x.Kind
	}
	return BuildFailed_Compilation_Error_KIND_UNSPECIFIED
}

func (x *BuildFailed_Compilation_Error) GetFile() string {
	if x != nil {
		return x.File
	}
	return ""
}

func (x *BuildFailed_Compilation_Error) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *BuildFailed_Compilation_Error) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BuildFailed_Compilation_Error) GetPosition() *BuildFailed_Compilation_Error_Position {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *BuildFailed_Compilation_Error) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

// Position locates the error in the file.
type BuildFailed_Compilation_Error_Position struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 1-based line number.
	Line uint32 `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	// 1-based column number.
	Column uint32 `protobuf:"varint,2,opt,name=column,proto3" json:"column,omitempty"`
	// JSONPath-style path of the offending element within the document,
	// when known.
	Path          string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildFailed_Compilation_Error_Position) Reset() {
	*x = BuildFailed_Compilation_Error_Position{}
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildFailed_Compilation_Error_Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildFailed_Compilation_Error_Position) ProtoMessage() {}

func (x *BuildFailed_Compilation_Error_Position) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildFailed_Compilation_Error_Position.ProtoReflect.Descriptor instead.
func (*BuildFailed_Compilation_Error_Position) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP(), []int{6, 0, 0, 0}
}

func (x *BuildFailed_Compilation_Error_Position) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *BuildFailed_Compilation_Error_Position) GetColumn() uint32 {
	if x != nil {
		return x.Column
	}
	return 0
}

func (x *BuildFailed_Compilation_Error_Position) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

var File_cerbos_cloud_notifications_v1_notifications_proto protoreflect.FileDescriptor

const file_cerbos_cloud_notifications_v1_notifications_proto_rawDesc = "" +
	"\n" +
	"1cerbos/cloud/notifications/v1/notifications.proto\x12\x1dcerbos.cloud.notifications.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x80\x11\n" +
	"\x05Event\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{12}$R\x02id\x12H\n" +
	"\x04type\x18\x02 \x01(\x0e2(.cerbos.cloud.notifications.v1.EventTypeB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04type\x12C\n" +
	"\voccurred_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"occurredAt\x128\n" +
	"\fworkspace_id\x18\x04 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{12}$R\vworkspaceId\x12?\n" +
	"\rdeployment_id\x18\x05 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{12}$H\x01R\fdeploymentId\x88\x01\x01\x12\x1f\n" +
	"\x04link\x18\x06 \x01(\tB\v\xbaH\br\x06\x18\x80 \x88\x01\x01R\x04link\x12O\n" +
	"\fbuild_failed\x18\n" +
	" \x01(\v2*.cerbos.cloud.notifications.v1.BuildFailedH\x00R\vbuildFailed\x12X\n" +
	"\x0fbuild_succeeded\x18\v \x01(\v2-.cerbos.cloud.notifications.v1.BuildSucceededH\x00R\x0ebuildSucceeded\x12X\n" +
	"\x0fbundle_promoted\x18\f \x01(\v2-.cerbos.cloud.notifications.v1.BundlePromotedH\x00R\x0ebundlePromoted\x12a\n" +
	"\x12credential_created\x18\r \x01(\v20.cerbos.cloud.notifications.v1.CredentialCreatedH\x00R\x11credentialCreated\x12a\n" +
	"\x12credential_deleted\x18\x0e \x01(\v20.cerbos.cloud.notifications.v1.CredentialDeletedH\x00R\x11credentialDeleted\x12O\n" +
	"\fmember_added\x18\x0f \x01(\v2*.cerbos.cloud.notifications.v1.MemberAddedH\x00R\vmemberAdded\x12U\n" +
	"\x0emember_removed\x18\x10 \x01(\v2,.cerbos.cloud.notifications.v1.MemberRemovedH\x00R\rmemberRemoved\x12[\n" +
	"\x10channel_disabled\x18\x11 \x01(\v2..cerbos.cloud.notifications.v1.ChannelDisabledH\x00R\x0fchannelDisabled\x12I\n" +
	"\n" +
	"test_fired\x18\x12 \x01(\v2(.cerbos.cloud.notifications.v1.TestFiredH\x00R\ttestFired\x12h\n" +
	"\x15deployment_fleet_dark\x18\x13 \x01(\v22.cerbos.cloud.notifications.v1.DeploymentFleetDarkH\x00R\x13deploymentFleetDark\x12t\n" +
	"\x19deployment_bundle_lagging\x18\x14 \x01(\v26.cerbos.cloud.notifications.v1.DeploymentBundleLaggingH\x00R\x17deploymentBundleLagging:\x85\x06\xbaH\x81\x06\x1a\xee\x04\n" +
	"\x1aevent.type_matches_payload\x12)the payload must be the one named by type\x1a\xa4\x04(this.type == 1) == has(this.build_failed) && (this.type == 2) == has(this.build_succeeded) && (this.type == 3) == has(this.bundle_promoted) && (this.type == 4) == has(this.credential_created) && (this.type == 5) == has(this.credential_deleted) && (this.type == 6) == has(this.member_added) && (this.type == 7) == has(this.member_removed) && (this.type == 8) == has(this.channel_disabled) && (this.type == 9) == has(this.test_fired) && (this.type == 10) == has(this.deployment_fleet_dark) && (this.type == 11) == has(this.deployment_bundle_lagging)\x1a\x8d\x01\n" +
	"\x17event.deployment_scoped\x12:deployment_id is required for bundle and deployment events\x1a6!(this.type in [3, 10, 11]) || has(this.deployment_id)B\x10\n" +
	"\apayload\x12\x05\xbaH\x02\b\x01B\x10\n" +
	"\x0e_deployment_id\"\x83\x01\n" +
	"\x05Actor\x124\n" +
	"\tmember_id\x18\x01 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{12}$H\x00R\bmemberId\x124\n" +
	"\tclient_id\x18\x02 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{12}$H\x00R\bclientIdB\x0e\n" +
	"\x05actor\x12\x05\xbaH\x02\b\x01\"`\n" +
	"\x06Member\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{12}$R\x02id\x12%\n" +
	"\x05email\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x18\x80\x02`\x01H\x00R\x05email\x88\x01\x01B\b\n" +
	"\x06_email\"\xb4\x01\n" +
	"\x05Build\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{16}$R\x02id\x12=\n" +
	"\tstore_ids\x18\x02 \x03(\tB \xbaH\x1d\x92\x01\x1a\b\x01\x10d\x18\x01\"\x12r\x102\x0e^[0-9A-Z]{12}$R\bstoreIds\x12E\n" +
	"\x0edeployment_ids\x18\x03 \x03(\tB\x1e\xbaH\x1b\x92\x01\x18\x10d\x18\x01\"\x12r\x102\x0e^[0-9A-Z]{12}$R\rdeploymentIds\"\xbc\x01\n" +
	"\tTestTally\x12\x1f\n" +
	"\vtests_count\x18\x01 \x01(\rR\n" +
	"testsCount\x12#\n" +
	"\rskipped_count\x18\x02 \x01(\rR\fskippedCount\x12!\n" +
	"\fpassed_count\x18\x03 \x01(\rR\vpassedCount\x12!\n" +
	"\ffailed_count\x18\x04 \x01(\rR\vfailedCount\x12#\n" +
	"\rerrored_count\x18\x05 \x01(\rR\ferroredCount\"\x96\x01\n" +
	"\tCondition\x12O\n" +
	"\x05state\x18\x01 \x01(\x0e2-.cerbos.cloud.notifications.v1.ConditionStateB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x05state\x128\n" +
	"\x05since\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\x05since\"\xef\t\n" +
	"\vBuildFailed\x12B\n" +
	"\x05build\x18\x01 \x01(\v2$.cerbos.cloud.notifications.v1.BuildB\x06\xbaH\x03\xc8\x01\x01R\x05build\x12Z\n" +
	"\vcompilation\x18\x02 \x01(\v26.cerbos.cloud.notifications.v1.BuildFailed.CompilationH\x00R\vcompilation\x12\xd6\x01\n" +
	"\x05tests\x18\x03 \x01(\v2(.cerbos.cloud.notifications.v1.TestTallyB\x93\x01\xbaH\x8f\x01\xba\x01\x8b\x01\n" +
	"\x1ebuild_failed.tests.some_failed\x12<a test failure must have at least one failed or errored test\x1a+this.failed_count + this.errored_count > 0uH\x00R\x05tests\x1a\xd4\x06\n" +
	"\vCompilation\x12`\n" +
	"\x06errors\x18\x01 \x03(\v2<.cerbos.cloud.notifications.v1.BuildFailed.Compilation.ErrorB\n" +
	"\xbaH\a\x92\x01\x04\b\x01\x10dR\x06errors\x12(\n" +
	"\verror_count\x18\x02 \x01(\rB\a\xbaH\x04*\x02 \x00R\n" +
	"errorCount\x1a\xb8\x05\n" +
	"\x05Error\x12a\n" +
	"\x04kind\x18\x01 \x01(\x0e2A.cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.KindB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x04kind\x12\x1c\n" +
	"\x04file\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\bR\x04file\x12 \n" +
	"\x05error\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02R\x05error\x12*\n" +
	"\vdescription\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80 R\vdescription\x12f\n" +
	"\bposition\x18\x05 \x01(\v2E.cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.PositionH\x00R\bposition\x88\x01\x01\x12\"\n" +
	"\acontext\x18\x06 \x01(\tB\b\xbaH\x05r\x03\x18\x80 R\acontext\x1af\n" +
	"\bPosition\x12\x1b\n" +
	"\x04line\x18\x01 \x01(\rB\a\xbaH\x04*\x02 \x00R\x04line\x12\x1f\n" +
	"\x06column\x18\x02 \x01(\rB\a\xbaH\x04*\x02 \x00R\x06column\x12\x1c\n" +
	"\x04path\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\x04path\"\xde\x01\n" +
	"\x04Kind\x12\x14\n" +
	"\x10KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12KIND_COMPILE_ERROR\x10\x01\x12\x15\n" +
	"\x11KIND_LOAD_FAILURE\x10\x02\x12\x1d\n" +
	"\x19KIND_DUPLICATE_DEFINITION\x10\x03\x12\x17\n" +
	"\x13KIND_MISSING_IMPORT\x10\x04\x12\x16\n" +
	"\x12KIND_MISSING_SCOPE\x10\x05\x12#\n" +
	"\x1fKIND_SCOPE_PERMISSIONS_CONFLICT\x10\x06\x12\x1c\n" +
	"\x18KIND_DISABLED_DEFINITION\x10\aB\v\n" +
	"\t_positionB\x10\n" +
	"\afailure\x12\x05\xbaH\x02\b\x01\"\xa3\x01\n" +
	"\x0eBuildSucceeded\x12B\n" +
	"\x05build\x18\x01 \x01(\v2$.cerbos.cloud.notifications.v1.BuildB\x06\xbaH\x03\xc8\x01\x01R\x05build\x12C\n" +
	"\x05tests\x18\x02 \x01(\v2(.cerbos.cloud.notifications.v1.TestTallyH\x00R\x05tests\x88\x01\x01B\b\n" +
	"\x06_tests\"\xa0\x01\n" +
	"\x0eBundlePromoted\x120\n" +
	"\bbuild_id\x18\x01 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{16}$R\abuildId\x12F\n" +
	"\x11previous_build_id\x18\x02 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{16}$H\x00R\x0fpreviousBuildId\x88\x01\x01B\x14\n" +
	"\x12_previous_build_id\"\xb7\x01\n" +
	"\x11CredentialCreated\x122\n" +
	"\tclient_id\x18\x01 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{12}$R\bclientId\x12*\n" +
	"\vdescription\x18\x02 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x02R\vdescription\x12B\n" +
	"\x05actor\x18\x03 \x01(\v2$.cerbos.cloud.notifications.v1.ActorB\x06\xbaH\x03\xc8\x01\x01R\x05actor\"\x8b\x01\n" +
	"\x11CredentialDeleted\x122\n" +
	"\tclient_id\x18\x01 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{12}$R\bclientId\x12B\n" +
	"\x05actor\x18\x02 \x01(\v2$.cerbos.cloud.notifications.v1.ActorB\x06\xbaH\x03\xc8\x01\x01R\x05actor\"\xf1\x01\n" +
	"\vMemberAdded\x12E\n" +
	"\x06member\x18\x01 \x01(\v2%.cerbos.cloud.notifications.v1.MemberB\x06\xbaH\x03\xc8\x01\x01R\x06member\x12W\n" +
	"\x05roles\x18\x02 \x03(\x0e2,.cerbos.cloud.notifications.v1.WorkspaceRoleB\x13\xbaH\x10\x92\x01\r\b\x01\x18\x01\"\a\x82\x01\x04\x10\x01 \x00R\x05roles\x12B\n" +
	"\x05actor\x18\x03 \x01(\v2$.cerbos.cloud.notifications.v1.ActorB\x06\xbaH\x03\xc8\x01\x01R\x05actor\"\xf3\x01\n" +
	"\rMemberRemoved\x12E\n" +
	"\x06member\x18\x01 \x01(\v2%.cerbos.cloud.notifications.v1.MemberB\x06\xbaH\x03\xc8\x01\x01R\x06member\x12W\n" +
	"\x05roles\x18\x02 \x03(\x0e2,.cerbos.cloud.notifications.v1.WorkspaceRoleB\x13\xbaH\x10\x92\x01\r\b\x01\x18\x01\"\a\x82\x01\x04\x10\x01 \x00R\x05roles\x12B\n" +
	"\x05actor\x18\x03 \x01(\v2$.cerbos.cloud.notifications.v1.ActorB\x06\xbaH\x03\xc8\x01\x01R\x05actor\"\x86\x02\n" +
	"\x0fChannelDisabled\x124\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{12}$R\tchannelId\x12Y\n" +
	"\x06reason\x18\x02 \x01(\x0e25.cerbos.cloud.notifications.v1.ChannelDisabled.ReasonB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x06reason\x12\"\n" +
	"\adetails\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80 R\adetails\">\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18REASON_DELIVERY_FAILURES\x10\x01\"\x85\x01\n" +
	"\tTestFired\x124\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{12}$R\tchannelId\x12B\n" +
	"\x05actor\x18\x02 \x01(\v2$.cerbos.cloud.notifications.v1.ActorB\x06\xbaH\x03\xc8\x01\x01R\x05actor\"e\n" +
	"\x13DeploymentFleetDark\x12N\n" +
	"\tcondition\x18\x01 \x01(\v2(.cerbos.cloud.notifications.v1.ConditionB\x06\xbaH\x03\xc8\x01\x01R\tcondition\"i\n" +
	"\x17DeploymentBundleLagging\x12N\n" +
	"\tcondition\x18\x01 \x01(\v2(.cerbos.cloud.notifications.v1.ConditionB\x06\xbaH\x03\xc8\x01\x01R\tcondition*\x92\x03\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EVENT_TYPE_BUILD_FAILED\x10\x01\x12\x1e\n" +
	"\x1aEVENT_TYPE_BUILD_SUCCEEDED\x10\x02\x12\x1e\n" +
	"\x1aEVENT_TYPE_BUNDLE_PROMOTED\x10\x03\x12!\n" +
	"\x1dEVENT_TYPE_CREDENTIAL_CREATED\x10\x04\x12!\n" +
	"\x1dEVENT_TYPE_CREDENTIAL_DELETED\x10\x05\x12\x1b\n" +
	"\x17EVENT_TYPE_MEMBER_ADDED\x10\x06\x12\x1d\n" +
	"\x19EVENT_TYPE_MEMBER_REMOVED\x10\a\x12\x1f\n" +
	"\x1bEVENT_TYPE_CHANNEL_DISABLED\x10\b\x12\x19\n" +
	"\x15EVENT_TYPE_TEST_FIRED\x10\t\x12$\n" +
	" EVENT_TYPE_DEPLOYMENT_FLEET_DARK\x10\n" +
	"\x12(\n" +
	"$EVENT_TYPE_DEPLOYMENT_BUNDLE_LAGGING\x10\v*k\n" +
	"\x0eConditionState\x12\x1f\n" +
	"\x1bCONDITION_STATE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17CONDITION_STATE_ENTERED\x10\x01\x12\x1b\n" +
	"\x17CONDITION_STATE_CLEARED\x10\x02*\x9e\x01\n" +
	"\rWorkspaceRole\x12\x1e\n" +
	"\x1aWORKSPACE_ROLE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14WORKSPACE_ROLE_OWNER\x10\x01\x12\x19\n" +
	"\x15WORKSPACE_ROLE_VIEWER\x10\x02\x12\x1c\n" +
	"\x18WORKSPACE_ROLE_DEVELOPER\x10\x03\x12\x1a\n" +
	"\x16WORKSPACE_ROLE_ANALYST\x10\x04B\x9c\x01\n" +
	"%dev.cerbos.api.cloud.v1.notificationsZOgithub.com/cerbos/cloud-api/genpb/cerbos/cloud/notifications/v1;notificationsv1\xaa\x02!Cerbos.Api.Cloud.V1.Notificationsb\x06proto3"

var (
	file_cerbos_cloud_notifications_v1_notifications_proto_rawDescOnce sync.Once
	file_cerbos_cloud_notifications_v1_notifications_proto_rawDescData []byte
)

func file_cerbos_cloud_notifications_v1_notifications_proto_rawDescGZIP() []byte {
	file_cerbos_cloud_notifications_v1_notifications_proto_rawDescOnce.Do(func() {
		file_cerbos_cloud_notifications_v1_notifications_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbos_cloud_notifications_v1_notifications_proto_rawDesc), len(file_cerbos_cloud_notifications_v1_notifications_proto_rawDesc)))
	})
	return file_cerbos_cloud_notifications_v1_notifications_proto_rawDescData
}

var file_cerbos_cloud_notifications_v1_notifications_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_cerbos_cloud_notifications_v1_notifications_proto_goTypes = []any{
	(EventType)(0),                                 // 0: cerbos.cloud.notifications.v1.EventType
	(ConditionState)(0),                            // 1: cerbos.cloud.notifications.v1.ConditionState
	(WorkspaceRole)(0),                             // 2: cerbos.cloud.notifications.v1.WorkspaceRole
	(BuildFailed_Compilation_Error_Kind)(0),        // 3: cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.Kind
	(ChannelDisabled_Reason)(0),                    // 4: cerbos.cloud.notifications.v1.ChannelDisabled.Reason
	(*Event)(nil),                                  // 5: cerbos.cloud.notifications.v1.Event
	(*Actor)(nil),                                  // 6: cerbos.cloud.notifications.v1.Actor
	(*Member)(nil),                                 // 7: cerbos.cloud.notifications.v1.Member
	(*Build)(nil),                                  // 8: cerbos.cloud.notifications.v1.Build
	(*TestTally)(nil),                              // 9: cerbos.cloud.notifications.v1.TestTally
	(*Condition)(nil),                              // 10: cerbos.cloud.notifications.v1.Condition
	(*BuildFailed)(nil),                            // 11: cerbos.cloud.notifications.v1.BuildFailed
	(*BuildSucceeded)(nil),                         // 12: cerbos.cloud.notifications.v1.BuildSucceeded
	(*BundlePromoted)(nil),                         // 13: cerbos.cloud.notifications.v1.BundlePromoted
	(*CredentialCreated)(nil),                      // 14: cerbos.cloud.notifications.v1.CredentialCreated
	(*CredentialDeleted)(nil),                      // 15: cerbos.cloud.notifications.v1.CredentialDeleted
	(*MemberAdded)(nil),                            // 16: cerbos.cloud.notifications.v1.MemberAdded
	(*MemberRemoved)(nil),                          // 17: cerbos.cloud.notifications.v1.MemberRemoved
	(*ChannelDisabled)(nil),                        // 18: cerbos.cloud.notifications.v1.ChannelDisabled
	(*TestFired)(nil),                              // 19: cerbos.cloud.notifications.v1.TestFired
	(*DeploymentFleetDark)(nil),                    // 20: cerbos.cloud.notifications.v1.DeploymentFleetDark
	(*DeploymentBundleLagging)(nil),                // 21: cerbos.cloud.notifications.v1.DeploymentBundleLagging
	(*BuildFailed_Compilation)(nil),                // 22: cerbos.cloud.notifications.v1.BuildFailed.Compilation
	(*BuildFailed_Compilation_Error)(nil),          // 23: cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error
	(*BuildFailed_Compilation_Error_Position)(nil), // 24: cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.Position
	(*timestamppb.Timestamp)(nil),                  // 25: google.protobuf.Timestamp
}
var file_cerbos_cloud_notifications_v1_notifications_proto_depIdxs = []int32{
	0,  // 0: cerbos.cloud.notifications.v1.Event.type:type_name -> cerbos.cloud.notifications.v1.EventType
	25, // 1: cerbos.cloud.notifications.v1.Event.occurred_at:type_name -> google.protobuf.Timestamp
	11, // 2: cerbos.cloud.notifications.v1.Event.build_failed:type_name -> cerbos.cloud.notifications.v1.BuildFailed
	12, // 3: cerbos.cloud.notifications.v1.Event.build_succeeded:type_name -> cerbos.cloud.notifications.v1.BuildSucceeded
	13, // 4: cerbos.cloud.notifications.v1.Event.bundle_promoted:type_name -> cerbos.cloud.notifications.v1.BundlePromoted
	14, // 5: cerbos.cloud.notifications.v1.Event.credential_created:type_name -> cerbos.cloud.notifications.v1.CredentialCreated
	15, // 6: cerbos.cloud.notifications.v1.Event.credential_deleted:type_name -> cerbos.cloud.notifications.v1.CredentialDeleted
	16, // 7: cerbos.cloud.notifications.v1.Event.member_added:type_name -> cerbos.cloud.notifications.v1.MemberAdded
	17, // 8: cerbos.cloud.notifications.v1.Event.member_removed:type_name -> cerbos.cloud.notifications.v1.MemberRemoved
	18, // 9: cerbos.cloud.notifications.v1.Event.channel_disabled:type_name -> cerbos.cloud.notifications.v1.ChannelDisabled
	19, // 10: cerbos.cloud.notifications.v1.Event.test_fired:type_name -> cerbos.cloud.notifications.v1.TestFired
	20, // 11: cerbos.cloud.notifications.v1.Event.deployment_fleet_dark:type_name -> cerbos.cloud.notifications.v1.DeploymentFleetDark
	21, // 12: cerbos.cloud.notifications.v1.Event.deployment_bundle_lagging:type_name -> cerbos.cloud.notifications.v1.DeploymentBundleLagging
	1,  // 13: cerbos.cloud.notifications.v1.Condition.state:type_name -> cerbos.cloud.notifications.v1.ConditionState
	25, // 14: cerbos.cloud.notifications.v1.Condition.since:type_name -> google.protobuf.Timestamp
	8,  // 15: cerbos.cloud.notifications.v1.BuildFailed.build:type_name -> cerbos.cloud.notifications.v1.Build
	22, // 16: cerbos.cloud.notifications.v1.BuildFailed.compilation:type_name -> cerbos.cloud.notifications.v1.BuildFailed.Compilation
	9,  // 17: cerbos.cloud.notifications.v1.BuildFailed.tests:type_name -> cerbos.cloud.notifications.v1.TestTally
	8,  // 18: cerbos.cloud.notifications.v1.BuildSucceeded.build:type_name -> cerbos.cloud.notifications.v1.Build
	9,  // 19: cerbos.cloud.notifications.v1.BuildSucceeded.tests:type_name -> cerbos.cloud.notifications.v1.TestTally
	6,  // 20: cerbos.cloud.notifications.v1.CredentialCreated.actor:type_name -> cerbos.cloud.notifications.v1.Actor
	6,  // 21: cerbos.cloud.notifications.v1.CredentialDeleted.actor:type_name -> cerbos.cloud.notifications.v1.Actor
	7,  // 22: cerbos.cloud.notifications.v1.MemberAdded.member:type_name -> cerbos.cloud.notifications.v1.Member
	2,  // 23: cerbos.cloud.notifications.v1.MemberAdded.roles:type_name -> cerbos.cloud.notifications.v1.WorkspaceRole
	6,  // 24: cerbos.cloud.notifications.v1.MemberAdded.actor:type_name -> cerbos.cloud.notifications.v1.Actor
	7,  // 25: cerbos.cloud.notifications.v1.MemberRemoved.member:type_name -> cerbos.cloud.notifications.v1.Member
	2,  // 26: cerbos.cloud.notifications.v1.MemberRemoved.roles:type_name -> cerbos.cloud.notifications.v1.WorkspaceRole
	6,  // 27: cerbos.cloud.notifications.v1.MemberRemoved.actor:type_name -> cerbos.cloud.notifications.v1.Actor
	4,  // 28: cerbos.cloud.notifications.v1.ChannelDisabled.reason:type_name -> cerbos.cloud.notifications.v1.ChannelDisabled.Reason
	6,  // 29: cerbos.cloud.notifications.v1.TestFired.actor:type_name -> cerbos.cloud.notifications.v1.Actor
	10, // 30: cerbos.cloud.notifications.v1.DeploymentFleetDark.condition:type_name -> cerbos.cloud.notifications.v1.Condition
	10, // 31: cerbos.cloud.notifications.v1.DeploymentBundleLagging.condition:type_name -> cerbos.cloud.notifications.v1.Condition
	23, // 32: cerbos.cloud.notifications.v1.BuildFailed.Compilation.errors:type_name -> cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error
	3,  // 33: cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.kind:type_name -> cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.Kind
	24, // 34: cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.position:type_name -> cerbos.cloud.notifications.v1.BuildFailed.Compilation.Error.Position
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_cerbos_cloud_notifications_v1_notifications_proto_init() }
func file_cerbos_cloud_notifications_v1_notifications_proto_init() {
	if File_cerbos_cloud_notifications_v1_notifications_proto != nil {
		return
	}
	file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[0].OneofWrappers = []any{
		(*Event_BuildFailed)(nil),
		(*Event_BuildSucceeded)(nil),
		(*Event_BundlePromoted)(nil),
		(*Event_CredentialCreated)(nil),
		(*Event_CredentialDeleted)(nil),
		(*Event_MemberAdded)(nil),
		(*Event_MemberRemoved)(nil),
		(*Event_ChannelDisabled)(nil),
		(*Event_TestFired)(nil),
		(*Event_DeploymentFleetDark)(nil),
		(*Event_DeploymentBundleLagging)(nil),
	}
	file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[1].OneofWrappers = []any{
		(*Actor_MemberId)(nil),
		(*Actor_ClientId)(nil),
	}
	file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[2].OneofWrappers = []any{}
	file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[6].OneofWrappers = []any{
		(*BuildFailed_Compilation_)(nil),
		(*BuildFailed_Tests)(nil),
	}
	file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[7].OneofWrappers = []any{}
	file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[8].OneofWrappers = []any{}
	file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbos_cloud_notifications_v1_notifications_proto_rawDesc), len(file_cerbos_cloud_notifications_v1_notifications_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cerbos_cloud_notifications_v1_notifications_proto_goTypes,
		DependencyIndexes: file_cerbos_cloud_notifications_v1_notifications_proto_depIdxs,
		EnumInfos:         file_cerbos_cloud_notifications_v1_notifications_proto_enumTypes,
		MessageInfos:      file_cerbos_cloud_notifications_v1_notifications_proto_msgTypes,
	}.Build()
	File_cerbos_cloud_notifications_v1_notifications_proto = out.File
	file_cerbos_cloud_notifications_v1_notifications_proto_goTypes = nil
	file_cerbos_cloud_notifications_v1_notifications_proto_depIdxs = nil
}
