// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0
// Source: cerbos/cloud/notifications/v1/notifications.proto

package notificationsv1

import (
	hash "hash"
)

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Event) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_Event_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Actor) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_Actor_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Member) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_Member_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Build) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_Build_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *TestTally) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_TestTally_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Condition) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_Condition_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BuildFailed) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_BuildFailed_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BuildFailed_Compilation) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_BuildFailed_Compilation_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BuildFailed_Compilation_Error) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_BuildFailed_Compilation_Error_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BuildFailed_Compilation_Error_Position) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_BuildFailed_Compilation_Error_Position_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BuildSucceeded) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_BuildSucceeded_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *BundlePromoted) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_BundlePromoted_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *CredentialCreated) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_CredentialCreated_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *CredentialDeleted) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_CredentialDeleted_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *MemberAdded) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_MemberAdded_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *MemberRemoved) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_MemberRemoved_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *ChannelDisabled) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_ChannelDisabled_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *TestFired) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_TestFired_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *DeploymentFleetDark) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_DeploymentFleetDark_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *DeploymentBundleLagging) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_DeploymentBundleLagging_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AccessRequestPending) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_AccessRequestPending_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AccessRequestApproved) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_AccessRequestApproved_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AccessRequestDenied) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_AccessRequestDenied_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AccessRequestExpired) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_AccessRequestExpired_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AccessRequestCancelled) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_AccessRequestCancelled_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AccessRequestSigningKeyExpiring) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_notifications_v1_AccessRequestSigningKeyExpiring_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}
