// Code generated by protoc-gen-go-hashpb. DO NOT EDIT.
// protoc-gen-go-hashpb v0.5.0
// Source: cerbos/cloud/accessrequest/v1/accessrequest.proto

package accessrequestv1

import (
	hash "hash"
)

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AccessRequestMarker) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_accessrequest_v1_AccessRequestMarker_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *DeniedEvaluation) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_accessrequest_v1_DeniedEvaluation_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Actor) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_accessrequest_v1_Actor_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *Approval) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_accessrequest_v1_Approval_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *AccessRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_accessrequest_v1_AccessRequest_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *CancelAccessRequestRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_accessrequest_v1_CancelAccessRequestRequest_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *CancelAccessRequestResponse) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_accessrequest_v1_CancelAccessRequestResponse_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *GetAccessRequestRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_accessrequest_v1_GetAccessRequestRequest_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *GetAccessRequestResponse) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_accessrequest_v1_GetAccessRequestResponse_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *SubmitAccessRequestRequest) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_accessrequest_v1_SubmitAccessRequestRequest_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}

// HashPB computes a hash of the message using the given hash function
// The ignore set must contain fully-qualified field names (pkg.msg.field) that should be ignored from the hash
func (m *SubmitAccessRequestResponse) HashPB(hasher hash.Hash, ignore map[string]struct{}) {
	if m != nil {
		b := hashpb_bufPool.Get().(*[10]byte)
		cerbos_cloud_accessrequest_v1_SubmitAccessRequestResponse_hashpb_sum(m, hasher, ignore, b)
		hashpb_bufPool.Put(b)
	}
}
