// Copyright 2021-2026 Zenauth Ltd.
// SPDX-License-Identifier: Apache-2.0

// Access requests: the PEP-facing contract for asking Cerbos Hub for the
// access a requestable deny withheld.
//
// A requestable deny is a deny decision whose rule declared an escalation
// marker in the reserved `cerbos.accessRequest` output. The application (the
// PEP) submits that denied evaluation here as an access request. Hub verifies
// it against the decision log entry it claims to be bound to, routes it to an
// approver and, if the request is approved, issues a time-boxed approval
// token. Completion is reevaluation: the PEP presents the token in
// `aux_data.jwts["approval"]` on a fresh check and policy decides. Hub never
// answers "allowed" on its own, and every approval expires.
//
// # Identifiers
//
// Access request and approval ids are 12 characters from 0-9A-Z, like every
// other id shown in the Hub UI and API. Evaluation ids are the 26-character
// ULID call ids the PDP assigns to each check (`cerbos_call_id`) and records in
// its decision log.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: cerbos/cloud/accessrequest/v1/accessrequest.proto

package accessrequestv1

import (
	v1 "github.com/cerbos/cerbos/api/genpb/cerbos/engine/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status is where an access request is in its lifecycle.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	// Submitted and awaiting a decision.
	Status_STATUS_PENDING Status = 1
	// An approver accepted it; `AccessRequest.approval` is set. A revoked
	// approval keeps this status with `Approval.revoked` set.
	Status_STATUS_APPROVED Status = 2
	// An approver declined it.
	Status_STATUS_DENIED Status = 3
	// No decision was made before `AccessRequest.expires_at`. Derived from a
	// pending request past its expiry, never stored: a reader computes it and
	// Hub emits `access_request.expired` when it first notices.
	Status_STATUS_EXPIRED Status = 4
	// The submitter withdrew it while it was pending.
	Status_STATUS_CANCELLED Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_APPROVED",
		3: "STATUS_DENIED",
		4: "STATUS_EXPIRED",
		5: "STATUS_CANCELLED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PENDING":     1,
		"STATUS_APPROVED":    2,
		"STATUS_DENIED":      3,
		"STATUS_EXPIRED":     4,
		"STATUS_CANCELLED":   5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescGZIP(), []int{0}
}

// Verification is the outcome of matching a submitted access request against
// the decision log entry it claims to be bound to. Only a matched request's
// marker is authoritative for routing and TTL; until then Hub uses the
// workspace default route and caps the TTL at the workspace minimum.
type Verification int32

const (
	Verification_VERIFICATION_UNSPECIFIED Verification = 0
	// Not yet compared with the decision log.
	Verification_VERIFICATION_PENDING Verification = 1
	// The decision log entry exists and agrees with the submitted denial.
	Verification_VERIFICATION_MATCHED Verification = 2
	// The decision log entry was found and disagrees with the submitted
	// denial, or never arrived within Hub's verification budget.
	Verification_VERIFICATION_UNMATCHED Verification = 3
	// The decision log could not be consulted within Hub's verification budget.
	Verification_VERIFICATION_UNAVAILABLE Verification = 4
)

// Enum value maps for Verification.
var (
	Verification_name = map[int32]string{
		0: "VERIFICATION_UNSPECIFIED",
		1: "VERIFICATION_PENDING",
		2: "VERIFICATION_MATCHED",
		3: "VERIFICATION_UNMATCHED",
		4: "VERIFICATION_UNAVAILABLE",
	}
	Verification_value = map[string]int32{
		"VERIFICATION_UNSPECIFIED": 0,
		"VERIFICATION_PENDING":     1,
		"VERIFICATION_MATCHED":     2,
		"VERIFICATION_UNMATCHED":   3,
		"VERIFICATION_UNAVAILABLE": 4,
	}
)

func (x Verification) Enum() *Verification {
	p := new(Verification)
	*p = x
	return p
}

func (x Verification) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verification) Descriptor() protoreflect.EnumDescriptor {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_enumTypes[1].Descriptor()
}

func (Verification) Type() protoreflect.EnumType {
	return &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_enumTypes[1]
}

func (x Verification) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verification.Descriptor instead.
func (Verification) EnumDescriptor() ([]byte, []int) {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescGZIP(), []int{1}
}

// AccessRequestMarker is the escalation marker a DENY rule declares under the
// reserved `cerbos.accessRequest` output key: that the deny may be requested,
// who may approve it, how long an approval may last and why. Policy is the
// only source of these facts; the PDP passes them through unvalidated and Hub
// validates them here.
//
// In policy outputs `approval_ttl` is a Go duration string using `s`, `m` or
// `h` units, between `1m` and `720h` (for example `4h`). The PEP parses that
// string into this Duration when it submits the denied evaluation, and Hub
// parses the same syntax when it extracts the marker from the decision log
// during verification. In protojson a Duration is rendered in seconds, so
// `4h` appears as `"14400s"`.
type AccessRequestMarker struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Routing label for the approver of the request. Lowercase letters, digits,
	// `.`, `_` and `-`; 1 to 64 characters, starting with a letter or digit.
	Approver string `protobuf:"bytes,1,opt,name=approver,proto3" json:"approver,omitempty"`
	// Longest an approval of this request may last, between one minute and 30
	// days. Hub also caps it at the workspace maximum, and at the workspace
	// minimum until the request is verified as matched.
	ApprovalTtl *durationpb.Duration `protobuf:"bytes,2,opt,name=approval_ttl,json=approvalTtl,proto3" json:"approval_ttl,omitempty"`
	// Why the access needs approval, shown to the requester and the approver.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequestMarker) Reset() {
	*x = AccessRequestMarker{}
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequestMarker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequestMarker) ProtoMessage() {}

func (x *AccessRequestMarker) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequestMarker.ProtoReflect.Descriptor instead.
func (*AccessRequestMarker) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescGZIP(), []int{0}
}

func (x *AccessRequestMarker) GetApprover() string {
	if x != nil {
		return x.Approver
	}
	return ""
}

func (x *AccessRequestMarker) GetApprovalTtl() *durationpb.Duration {
	if x != nil {
		return x.ApprovalTtl
	}
	return nil
}

func (x *AccessRequestMarker) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// DeniedEvaluation is the denied check an access request is bound to, as the
// PEP saw it: the call id the PDP assigned, the principal, resource and
// actions it evaluated, and the escalation marker its deny rule emitted. Hub
// treats every field as a claim until verification compares it with the
// decision log entry that has the same evaluation id in the same workspace.
type DeniedEvaluation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The PDP's call id for the check: `cerbos_call_id` in the check response
	// and `call_id` in the decision log entry. A 26-character ULID.
	EvaluationId string `protobuf:"bytes,1,opt,name=evaluation_id,json=evaluationId,proto3" json:"evaluation_id,omitempty"`
	// When the PDP evaluated the check. A request submitted more than the
	// workspace's request window after this is rejected as expired.
	EvaluatedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=evaluated_at,json=evaluatedAt,proto3" json:"evaluated_at,omitempty"`
	// The principal the check was for, as sent to the PDP.
	Principal *v1.Principal `protobuf:"bytes,3,opt,name=principal,proto3" json:"principal,omitempty"`
	// The resource the check was for, as sent to the PDP.
	Resource *v1.Resource `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	// The actions the rule named by `rule_src` denied. At least one.
	Actions []string `protobuf:"bytes,5,rep,name=actions,proto3" json:"actions,omitempty"`
	// The escalation marker from the deny rule's `cerbos.accessRequest` output.
	Marker *AccessRequestMarker `protobuf:"bytes,6,opt,name=marker,proto3" json:"marker,omitempty"`
	// The `src` of the output entry the marker was taken from, which names the
	// rule that produced the final deny (for example
	// `resource.production_database.vdefault#write-requestable`). Outputs are
	// collected from every rule that activates, so this is how Hub tells the
	// authoritative marker from one emitted by a rule that did not decide.
	RuleSrc       string `protobuf:"bytes,7,opt,name=rule_src,json=ruleSrc,proto3" json:"rule_src,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeniedEvaluation) Reset() {
	*x = DeniedEvaluation{}
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeniedEvaluation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeniedEvaluation) ProtoMessage() {}

func (x *DeniedEvaluation) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeniedEvaluation.ProtoReflect.Descriptor instead.
func (*DeniedEvaluation) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescGZIP(), []int{1}
}

func (x *DeniedEvaluation) GetEvaluationId() string {
	if x != nil {
		return x.EvaluationId
	}
	return ""
}

func (x *DeniedEvaluation) GetEvaluatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EvaluatedAt
	}
	return nil
}

func (x *DeniedEvaluation) GetPrincipal() *v1.Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *DeniedEvaluation) GetResource() *v1.Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *DeniedEvaluation) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *DeniedEvaluation) GetMarker() *AccessRequestMarker {
	if x != nil {
		return x.Marker
	}
	return nil
}

func (x *DeniedEvaluation) GetRuleSrc() string {
	if x != nil {
		return x.RuleSrc
	}
	return ""
}

// Actor is the optional, client-supplied chain of who submitted the request
// on whose behalf: an agent acting for a person, a service acting for an
// agent. Hub stores it and shows it to approvers. It is never authorization
// input and Hub does not verify it; the principal the request is for is
// `DeniedEvaluation.principal`. The shape follows the AuthZEN ARAP actor.
type Actor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identifier of the actor in the caller's own terms.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Kind of actor in the caller's own terms, such as `user`, `agent` or
	// `service`.
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// The actors this one is acting for, outermost first. A chain is at most
	// three levels deep: this actor, the actors it acts for, and theirs.
	Act           []*Actor `protobuf:"bytes,3,rep,name=act,proto3" json:"act,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescGZIP(), []int{2}
}

func (x *Actor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Actor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Actor) GetAct() []*Actor {
	if x != nil {
		return x.Act
	}
	return nil
}

// Approval is the time-boxed record produced when an approver accepts an
// access request. It is input to the PEP's reevaluation, never an outcome by
// itself.
type Approval struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The approval's id. Also the token's `jti` claim.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// When the approver accepted the request.
	ApprovedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=approved_at,json=approvedAt,proto3" json:"approved_at,omitempty"`
	// When the approval ends: `approved_at` plus the effective TTL, or the
	// earlier time the approver chose. The token's `exp` claim.
	ApprovedUntil *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=approved_until,json=approvedUntil,proto3" json:"approved_until,omitempty"`
	// The approval token: a JWT signed by the workspace's key that carries the
	// claims the PDP policy pattern checks against the reevaluation (the claim
	// set is defined once, in the requestable denies documentation). The PEP
	// passes it as `aux_data.jwts["approval"]` on the reevaluation.
	//
	// Treat it as a credential: anyone holding it can complete the reevaluation
	// as the principal until `exp`, and Hub cannot revoke it before then. Do not
	// log it or store it beyond the reevaluation. Present in AccessRequestService
	// responses; always empty in notification events.
	Token string `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	// Whether the approval was revoked in Hub. The PDP verifies the token by
	// signature and `exp` only, so a revoked approval still evaluates until
	// `approved_until`; the PEP should stop presenting it.
	Revoked       bool `protobuf:"varint,5,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Approval) Reset() {
	*x = Approval{}
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Approval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Approval) ProtoMessage() {}

func (x *Approval) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Approval.ProtoReflect.Descriptor instead.
func (*Approval) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescGZIP(), []int{3}
}

func (x *Approval) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Approval) GetApprovedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedAt
	}
	return nil
}

func (x *Approval) GetApprovedUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ApprovedUntil
	}
	return nil
}

func (x *Approval) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Approval) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

// AccessRequest is the lifecycle object created when a principal, or an agent
// on their behalf, asks for the access a requestable deny withheld. It is
// bound to exactly one denied evaluation.
type AccessRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The request's id, assigned by Hub. Any API key of the same workspace can
	// read or cancel the request by this id.
	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status Status `protobuf:"varint,2,opt,name=status,proto3,enum=cerbos.cloud.accessrequest.v1.Status" json:"status,omitempty"`
	// The denied evaluation the request is bound to, as submitted.
	Denial       *DeniedEvaluation `protobuf:"bytes,3,opt,name=denial,proto3" json:"denial,omitempty"`
	Verification Verification      `protobuf:"varint,4,opt,name=verification,proto3,enum=cerbos.cloud.accessrequest.v1.Verification" json:"verification,omitempty"`
	// The submitter's reason for asking, shown to the approver.
	Justification string `protobuf:"bytes,5,opt,name=justification,proto3" json:"justification,omitempty"`
	// Who submitted the request on whose behalf, when the submitter said.
	Actor *Actor `protobuf:"bytes,6,opt,name=actor,proto3" json:"actor,omitempty"`
	// The approval, when `status` is STATUS_APPROVED.
	Approval *Approval `protobuf:"bytes,7,opt,name=approval,proto3" json:"approval,omitempty"`
	// When the request was submitted.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When a still-pending request stops being decidable and becomes
	// STATUS_EXPIRED: `created_at` plus the workspace's request window.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessRequest) Reset() {
	*x = AccessRequest{}
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessRequest) ProtoMessage() {}

func (x *AccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessRequest.ProtoReflect.Descriptor instead.
func (*AccessRequest) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescGZIP(), []int{4}
}

func (x *AccessRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessRequest) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

func (x *AccessRequest) GetDenial() *DeniedEvaluation {
	if x != nil {
		return x.Denial
	}
	return nil
}

func (x *AccessRequest) GetVerification() Verification {
	if x != nil {
		return x.Verification
	}
	return Verification_VERIFICATION_UNSPECIFIED
}

func (x *AccessRequest) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

func (x *AccessRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *AccessRequest) GetApproval() *Approval {
	if x != nil {
		return x.Approval
	}
	return nil
}

func (x *AccessRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AccessRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CancelAccessRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the request to cancel.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAccessRequestRequest) Reset() {
	*x = CancelAccessRequestRequest{}
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAccessRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAccessRequestRequest) ProtoMessage() {}

func (x *CancelAccessRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAccessRequestRequest.ProtoReflect.Descriptor instead.
func (*CancelAccessRequestRequest) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescGZIP(), []int{5}
}

func (x *CancelAccessRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type CancelAccessRequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The request, now STATUS_CANCELLED.
	AccessRequest *AccessRequest `protobuf:"bytes,1,opt,name=access_request,json=accessRequest,proto3" json:"access_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelAccessRequestResponse) Reset() {
	*x = CancelAccessRequestResponse{}
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelAccessRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelAccessRequestResponse) ProtoMessage() {}

func (x *CancelAccessRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelAccessRequestResponse.ProtoReflect.Descriptor instead.
func (*CancelAccessRequestResponse) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescGZIP(), []int{6}
}

func (x *CancelAccessRequestResponse) GetAccessRequest() *AccessRequest {
	if x != nil {
		return x.AccessRequest
	}
	return nil
}

type GetAccessRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Id of the request to read.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessRequestRequest) Reset() {
	*x = GetAccessRequestRequest{}
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessRequestRequest) ProtoMessage() {}

func (x *GetAccessRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessRequestRequest.ProtoReflect.Descriptor instead.
func (*GetAccessRequestRequest) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescGZIP(), []int{7}
}

func (x *GetAccessRequestRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAccessRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessRequest *AccessRequest         `protobuf:"bytes,1,opt,name=access_request,json=accessRequest,proto3" json:"access_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccessRequestResponse) Reset() {
	*x = GetAccessRequestResponse{}
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccessRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccessRequestResponse) ProtoMessage() {}

func (x *GetAccessRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccessRequestResponse.ProtoReflect.Descriptor instead.
func (*GetAccessRequestResponse) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescGZIP(), []int{8}
}

func (x *GetAccessRequestResponse) GetAccessRequest() *AccessRequest {
	if x != nil {
		return x.AccessRequest
	}
	return nil
}

type SubmitAccessRequestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caller-chosen key that makes the submission safe to retry. Resubmitting
	// with the same key for the same evaluation (evaluation id, principal id,
	// resource kind and id, actions) returns the request created the first time;
	// the same key for a different evaluation is ALREADY_EXISTS. Keys are scoped
	// to the calling API key. Without a key, a second submission for an
	// evaluation that already has a pending request returns that request.
	IdempotencyKey *string `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3,oneof" json:"idempotency_key,omitempty"`
	// The denied evaluation to request access for.
	Denial *DeniedEvaluation `protobuf:"bytes,2,opt,name=denial,proto3" json:"denial,omitempty"`
	// The submitter's reason for asking, shown to the approver.
	Justification string `protobuf:"bytes,3,opt,name=justification,proto3" json:"justification,omitempty"`
	// Who is submitting on whose behalf. Optional and unverified.
	Actor         *Actor `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAccessRequestRequest) Reset() {
	*x = SubmitAccessRequestRequest{}
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAccessRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAccessRequestRequest) ProtoMessage() {}

func (x *SubmitAccessRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAccessRequestRequest.ProtoReflect.Descriptor instead.
func (*SubmitAccessRequestRequest) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescGZIP(), []int{9}
}

func (x *SubmitAccessRequestRequest) GetIdempotencyKey() string {
	if x != nil && x.IdempotencyKey != nil {
		return *x.IdempotencyKey
	}
	return ""
}

func (x *SubmitAccessRequestRequest) GetDenial() *DeniedEvaluation {
	if x != nil {
		return x.Denial
	}
	return nil
}

func (x *SubmitAccessRequestRequest) GetJustification() string {
	if x != nil {
		return x.Justification
	}
	return ""
}

func (x *SubmitAccessRequestRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type SubmitAccessRequestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The request, STATUS_PENDING unless it is an earlier request returned by
	// idempotency.
	AccessRequest *AccessRequest `protobuf:"bytes,1,opt,name=access_request,json=accessRequest,proto3" json:"access_request,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitAccessRequestResponse) Reset() {
	*x = SubmitAccessRequestResponse{}
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitAccessRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitAccessRequestResponse) ProtoMessage() {}

func (x *SubmitAccessRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitAccessRequestResponse.ProtoReflect.Descriptor instead.
func (*SubmitAccessRequestResponse) Descriptor() ([]byte, []int) {
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescGZIP(), []int{10}
}

func (x *SubmitAccessRequestResponse) GetAccessRequest() *AccessRequest {
	if x != nil {
		return x.AccessRequest
	}
	return nil
}

var File_cerbos_cloud_accessrequest_v1_accessrequest_proto protoreflect.FileDescriptor

const file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDesc = "" +
	"\n" +
	"1cerbos/cloud/accessrequest/v1/accessrequest.proto\x12\x1dcerbos.cloud.accessrequest.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1dcerbos/engine/v1/engine.proto\x1a\x1bgoogle/api/visibility.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x01\n" +
	"\x13AccessRequestMarker\x12>\n" +
	"\bapprover\x18\x01 \x01(\tB\"\xbaH\x1fr\x1d2\x1b^[a-z0-9][a-z0-9._-]{0,63}$R\bapprover\x12R\n" +
	"\fapproval_ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationB\x14\xbaH\x11\xc8\x01\x01\xaa\x01\v\"\x05\b\x80\x9a\x9e\x012\x02\b<R\vapprovalTtl\x12 \n" +
	"\x06reason\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80\x04R\x06reason\"\xd3\x03\n" +
	"\x10DeniedEvaluation\x12I\n" +
	"\revaluation_id\x18\x01 \x01(\tB$\xbaH!r\x1f2\x1d^[0-7][0-9A-HJKMNP-TV-Z]{25}$R\fevaluationId\x12E\n" +
	"\fevaluated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\vevaluatedAt\x12A\n" +
	"\tprincipal\x18\x03 \x01(\v2\x1b.cerbos.engine.v1.PrincipalB\x06\xbaH\x03\xc8\x01\x01R\tprincipal\x12>\n" +
	"\bresource\x18\x04 \x01(\v2\x1a.cerbos.engine.v1.ResourceB\x06\xbaH\x03\xc8\x01\x01R\bresource\x12/\n" +
	"\aactions\x18\x05 \x03(\tB\x15\xbaH\x12\x92\x01\x0f\b\x01\x10d\x18\x01\"\ar\x05\x10\x01\x18\x80\x02R\aactions\x12R\n" +
	"\x06marker\x18\x06 \x01(\v22.cerbos.cloud.accessrequest.v1.AccessRequestMarkerB\x06\xbaH\x03\xc8\x01\x01R\x06marker\x12%\n" +
	"\brule_src\x18\a \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\bR\aruleSrc\"\xf1\x01\n" +
	"\x05Actor\x12\x1a\n" +
	"\x02id\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\bR\x02id\x12\x1b\n" +
	"\x04type\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18@R\x04type\x12\xae\x01\n" +
	"\x03act\x18\x03 \x03(\v2$.cerbos.cloud.accessrequest.v1.ActorBv\xbaHs\xba\x01k\n" +
	"\x0factor.max_depth\x12+an actor chain is at most three levels deep\x1a+this.all(a, a.act.all(b, size(b.act) == 0))\x92\x01\x02\x10\bR\x03act\"\xed\x02\n" +
	"\bApproval\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{12}$R\x02id\x12C\n" +
	"\vapproved_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"approvedAt\x12I\n" +
	"\x0eapproved_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\rapprovedUntil\x12\x1e\n" +
	"\x05token\x18\x04 \x01(\tB\b\xbaH\x05r\x03\x18\x80@R\x05token\x12\x18\n" +
	"\arevoked\x18\x05 \x01(\bR\arevoked:p\xbaHm\x1ak\n" +
	"\x17approval.until_after_at\x12(approved_until must be after approved_at\x1a&this.approved_until > this.approved_at\"\xe8\x06\n" +
	"\rAccessRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{12}$R\x02id\x12I\n" +
	"\x06status\x18\x02 \x01(\x0e2%.cerbos.cloud.accessrequest.v1.StatusB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\x06status\x12O\n" +
	"\x06denial\x18\x03 \x01(\v2/.cerbos.cloud.accessrequest.v1.DeniedEvaluationB\x06\xbaH\x03\xc8\x01\x01R\x06denial\x12[\n" +
	"\fverification\x18\x04 \x01(\x0e2+.cerbos.cloud.accessrequest.v1.VerificationB\n" +
	"\xbaH\a\x82\x01\x04\x10\x01 \x00R\fverification\x12.\n" +
	"\rjustification\x18\x05 \x01(\tB\b\xbaH\x05r\x03\x18\x80 R\rjustification\x12:\n" +
	"\x05actor\x18\x06 \x01(\v2$.cerbos.cloud.accessrequest.v1.ActorR\x05actor\x12C\n" +
	"\bapproval\x18\a \x01(\v2'.cerbos.cloud.accessrequest.v1.ApprovalR\bapproval\x12A\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedAt\x12A\n" +
	"\n" +
	"expires_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\texpiresAt:\xff\x01\xbaH\xfb\x01\x1a\x88\x01\n" +
	"$access_request.approval_iff_approved\x126approval is set exactly when status is STATUS_APPROVED\x1a((this.status == 2) == has(this.approval)\x1an\n" +
	"$access_request.expires_after_created\x12#expires_at must be after created_at\x1a!this.expires_at > this.created_at\"C\n" +
	"\x1aCancelAccessRequestRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{12}$R\x02id\"z\n" +
	"\x1bCancelAccessRequestResponse\x12[\n" +
	"\x0eaccess_request\x18\x01 \x01(\v2,.cerbos.cloud.accessrequest.v1.AccessRequestB\x06\xbaH\x03\xc8\x01\x01R\raccessRequest\"@\n" +
	"\x17GetAccessRequestRequest\x12%\n" +
	"\x02id\x18\x01 \x01(\tB\x15\xbaH\x12r\x102\x0e^[0-9A-Z]{12}$R\x02id\"w\n" +
	"\x18GetAccessRequestResponse\x12[\n" +
	"\x0eaccess_request\x18\x01 \x01(\v2,.cerbos.cloud.accessrequest.v1.AccessRequestB\x06\xbaH\x03\xc8\x01\x01R\raccessRequest\"\xa7\x02\n" +
	"\x1aSubmitAccessRequestRequest\x128\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x02H\x00R\x0eidempotencyKey\x88\x01\x01\x12O\n" +
	"\x06denial\x18\x02 \x01(\v2/.cerbos.cloud.accessrequest.v1.DeniedEvaluationB\x06\xbaH\x03\xc8\x01\x01R\x06denial\x12.\n" +
	"\rjustification\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\x80 R\rjustification\x12:\n" +
	"\x05actor\x18\x04 \x01(\v2$.cerbos.cloud.accessrequest.v1.ActorR\x05actorB\x12\n" +
	"\x10_idempotency_key\"z\n" +
	"\x1bSubmitAccessRequestResponse\x12[\n" +
	"\x0eaccess_request\x18\x01 \x01(\v2,.cerbos.cloud.accessrequest.v1.AccessRequestB\x06\xbaH\x03\xc8\x01\x01R\raccessRequest*\x86\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x13\n" +
	"\x0fSTATUS_APPROVED\x10\x02\x12\x11\n" +
	"\rSTATUS_DENIED\x10\x03\x12\x12\n" +
	"\x0eSTATUS_EXPIRED\x10\x04\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x05*\x9a\x01\n" +
	"\fVerification\x12\x1c\n" +
	"\x18VERIFICATION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14VERIFICATION_PENDING\x10\x01\x12\x18\n" +
	"\x14VERIFICATION_MATCHED\x10\x02\x12\x1a\n" +
	"\x16VERIFICATION_UNMATCHED\x10\x03\x12\x1c\n" +
	"\x18VERIFICATION_UNAVAILABLE\x10\x042\xd9\x03\n" +
	"\x14AccessRequestService\x12\x8e\x01\n" +
	"\x13CancelAccessRequest\x129.cerbos.cloud.accessrequest.v1.CancelAccessRequestRequest\x1a:.cerbos.cloud.accessrequest.v1.CancelAccessRequestResponse\"\x00\x12\x88\x01\n" +
	"\x10GetAccessRequest\x126.cerbos.cloud.accessrequest.v1.GetAccessRequestRequest\x1a7.cerbos.cloud.accessrequest.v1.GetAccessRequestResponse\"\x03\x90\x02\x01\x12\x8e\x01\n" +
	"\x13SubmitAccessRequest\x129.cerbos.cloud.accessrequest.v1.SubmitAccessRequestRequest\x1a:.cerbos.cloud.accessrequest.v1.SubmitAccessRequestResponse\"\x00\x1a\x14\xfa\xd2\xe4\x93\x02\x0e\x12\fEXPERIMENTALB\x9c\x01\n" +
	"%dev.cerbos.api.cloud.v1.accessrequestZOgithub.com/cerbos/cloud-api/genpb/cerbos/cloud/accessrequest/v1;accessrequestv1\xaa\x02!Cerbos.Api.Cloud.V1.AccessRequestb\x06proto3"

var (
	file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescOnce sync.Once
	file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescData []byte
)

func file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescGZIP() []byte {
	file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescOnce.Do(func() {
		file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDesc), len(file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDesc)))
	})
	return file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDescData
}

var file_cerbos_cloud_accessrequest_v1_accessrequest_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_cerbos_cloud_accessrequest_v1_accessrequest_proto_goTypes = []any{
	(Status)(0),                         // 0: cerbos.cloud.accessrequest.v1.Status
	(Verification)(0),                   // 1: cerbos.cloud.accessrequest.v1.Verification
	(*AccessRequestMarker)(nil),         // 2: cerbos.cloud.accessrequest.v1.AccessRequestMarker
	(*DeniedEvaluation)(nil),            // 3: cerbos.cloud.accessrequest.v1.DeniedEvaluation
	(*Actor)(nil),                       // 4: cerbos.cloud.accessrequest.v1.Actor
	(*Approval)(nil),                    // 5: cerbos.cloud.accessrequest.v1.Approval
	(*AccessRequest)(nil),               // 6: cerbos.cloud.accessrequest.v1.AccessRequest
	(*CancelAccessRequestRequest)(nil),  // 7: cerbos.cloud.accessrequest.v1.CancelAccessRequestRequest
	(*CancelAccessRequestResponse)(nil), // 8: cerbos.cloud.accessrequest.v1.CancelAccessRequestResponse
	(*GetAccessRequestRequest)(nil),     // 9: cerbos.cloud.accessrequest.v1.GetAccessRequestRequest
	(*GetAccessRequestResponse)(nil),    // 10: cerbos.cloud.accessrequest.v1.GetAccessRequestResponse
	(*SubmitAccessRequestRequest)(nil),  // 11: cerbos.cloud.accessrequest.v1.SubmitAccessRequestRequest
	(*SubmitAccessRequestResponse)(nil), // 12: cerbos.cloud.accessrequest.v1.SubmitAccessRequestResponse
	(*durationpb.Duration)(nil),         // 13: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),       // 14: google.protobuf.Timestamp
	(*v1.Principal)(nil),                // 15: cerbos.engine.v1.Principal
	(*v1.Resource)(nil),                 // 16: cerbos.engine.v1.Resource
}
var file_cerbos_cloud_accessrequest_v1_accessrequest_proto_depIdxs = []int32{
	13, // 0: cerbos.cloud.accessrequest.v1.AccessRequestMarker.approval_ttl:type_name -> google.protobuf.Duration
	14, // 1: cerbos.cloud.accessrequest.v1.DeniedEvaluation.evaluated_at:type_name -> google.protobuf.Timestamp
	15, // 2: cerbos.cloud.accessrequest.v1.DeniedEvaluation.principal:type_name -> cerbos.engine.v1.Principal
	16, // 3: cerbos.cloud.accessrequest.v1.DeniedEvaluation.resource:type_name -> cerbos.engine.v1.Resource
	2,  // 4: cerbos.cloud.accessrequest.v1.DeniedEvaluation.marker:type_name -> cerbos.cloud.accessrequest.v1.AccessRequestMarker
	4,  // 5: cerbos.cloud.accessrequest.v1.Actor.act:type_name -> cerbos.cloud.accessrequest.v1.Actor
	14, // 6: cerbos.cloud.accessrequest.v1.Approval.approved_at:type_name -> google.protobuf.Timestamp
	14, // 7: cerbos.cloud.accessrequest.v1.Approval.approved_until:type_name -> google.protobuf.Timestamp
	0,  // 8: cerbos.cloud.accessrequest.v1.AccessRequest.status:type_name -> cerbos.cloud.accessrequest.v1.Status
	3,  // 9: cerbos.cloud.accessrequest.v1.AccessRequest.denial:type_name -> cerbos.cloud.accessrequest.v1.DeniedEvaluation
	1,  // 10: cerbos.cloud.accessrequest.v1.AccessRequest.verification:type_name -> cerbos.cloud.accessrequest.v1.Verification
	4,  // 11: cerbos.cloud.accessrequest.v1.AccessRequest.actor:type_name -> cerbos.cloud.accessrequest.v1.Actor
	5,  // 12: cerbos.cloud.accessrequest.v1.AccessRequest.approval:type_name -> cerbos.cloud.accessrequest.v1.Approval
	14, // 13: cerbos.cloud.accessrequest.v1.AccessRequest.created_at:type_name -> google.protobuf.Timestamp
	14, // 14: cerbos.cloud.accessrequest.v1.AccessRequest.expires_at:type_name -> google.protobuf.Timestamp
	6,  // 15: cerbos.cloud.accessrequest.v1.CancelAccessRequestResponse.access_request:type_name -> cerbos.cloud.accessrequest.v1.AccessRequest
	6,  // 16: cerbos.cloud.accessrequest.v1.GetAccessRequestResponse.access_request:type_name -> cerbos.cloud.accessrequest.v1.AccessRequest
	3,  // 17: cerbos.cloud.accessrequest.v1.SubmitAccessRequestRequest.denial:type_name -> cerbos.cloud.accessrequest.v1.DeniedEvaluation
	4,  // 18: cerbos.cloud.accessrequest.v1.SubmitAccessRequestRequest.actor:type_name -> cerbos.cloud.accessrequest.v1.Actor
	6,  // 19: cerbos.cloud.accessrequest.v1.SubmitAccessRequestResponse.access_request:type_name -> cerbos.cloud.accessrequest.v1.AccessRequest
	7,  // 20: cerbos.cloud.accessrequest.v1.AccessRequestService.CancelAccessRequest:input_type -> cerbos.cloud.accessrequest.v1.CancelAccessRequestRequest
	9,  // 21: cerbos.cloud.accessrequest.v1.AccessRequestService.GetAccessRequest:input_type -> cerbos.cloud.accessrequest.v1.GetAccessRequestRequest
	11, // 22: cerbos.cloud.accessrequest.v1.AccessRequestService.SubmitAccessRequest:input_type -> cerbos.cloud.accessrequest.v1.SubmitAccessRequestRequest
	8,  // 23: cerbos.cloud.accessrequest.v1.AccessRequestService.CancelAccessRequest:output_type -> cerbos.cloud.accessrequest.v1.CancelAccessRequestResponse
	10, // 24: cerbos.cloud.accessrequest.v1.AccessRequestService.GetAccessRequest:output_type -> cerbos.cloud.accessrequest.v1.GetAccessRequestResponse
	12, // 25: cerbos.cloud.accessrequest.v1.AccessRequestService.SubmitAccessRequest:output_type -> cerbos.cloud.accessrequest.v1.SubmitAccessRequestResponse
	23, // [23:26] is the sub-list for method output_type
	20, // [20:23] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_cerbos_cloud_accessrequest_v1_accessrequest_proto_init() }
func file_cerbos_cloud_accessrequest_v1_accessrequest_proto_init() {
	if File_cerbos_cloud_accessrequest_v1_accessrequest_proto != nil {
		return
	}
	file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDesc), len(file_cerbos_cloud_accessrequest_v1_accessrequest_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cerbos_cloud_accessrequest_v1_accessrequest_proto_goTypes,
		DependencyIndexes: file_cerbos_cloud_accessrequest_v1_accessrequest_proto_depIdxs,
		EnumInfos:         file_cerbos_cloud_accessrequest_v1_accessrequest_proto_enumTypes,
		MessageInfos:      file_cerbos_cloud_accessrequest_v1_accessrequest_proto_msgTypes,
	}.Build()
	File_cerbos_cloud_accessrequest_v1_accessrequest_proto = out.File
	file_cerbos_cloud_accessrequest_v1_accessrequest_proto_goTypes = nil
	file_cerbos_cloud_accessrequest_v1_accessrequest_proto_depIdxs = nil
}
